@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

skinparam classFontColor red


title System-Landscape-Diagram-for-HCPC

Person(HCPCAdmin, "HCPC Admin", "The user that visits the website to manage ESC, District, and School setup, as well as billing, audits/revision and viewing detailed reports.")
Person(SchoolAdmin, "School Administrattion", "The user that visits the website to manage encounters, finances and providers.")
Person(Providers, "Providers", "The user that visits the website to manage encounters.")


Enterprise_Boundary(SB1, "EduDoc 4.0 Application"){

    System_Boundary(CoreSite, "EduDoc Portals (Split Portal Architecture)") {
        System(BreckenridgeCoreAdminPortal, "Admin Portal", "provides interface to manage provider, districts, billing, certain aspect related to encounters and other admin stuffs")
        System(BreckenridgeCoreSchoolPortal, "School District Portal", "provides means to manage District / School Related Information")
        System(BreckenridgeCoreProviderPortal, "Provider Portal", "provides means to mainly manage encounters")


    }

    System(api, "API", ".Net Web API")

    System_Boundary(CoreApplication, "Application") {
        System(servicelayer, "ServiceLayer", "Service layer for business logic")
        System(breckmodellayer, "Model", "Entities for Database Tables of the Core Application")
        SystemDb(breckdb, "Database", "Core Application Microsoft SQL Database")


    }

    System_Boundary(ConsoleJobs, "Console Jobs") {
        System(BillingSchedulesJob, "Job for Health Care Claim EDI Generation", "Generates 837 files based on district groups. These files are selvered to Ohio Medicaid.")
        System(RosterUploadJob, "Job for Roster Upload", "Handles Merging Students after Student Roster documents have been uploaded to the District Admin portal")
        System(ActivitySummaryJob, "Job for Process Activity Summary Data", "Caches Activity Summary data in order to optimize report performance.")
        System(AnnualTrainingsJob, "Job for Annual Trainings", "Handles generation of annual trainings required for providers.")
        System(PendingReferralsJob, "Job to Process Pending Referral Data", "Caches pending referral data in order to optimize report performance.")
        System(ProgressReportJob, "Job to Process Pending Referral Data", "Caches pending referral data in order to optimize report performance.")
        System(RetireEncounterJob, "Job to Retire Encounters", "Archives Encounters taht have passed the 365 day mark.")
        System(TherapySchedulesJob, "Job to Generate Encounters Ready For You", "Daily job that generates Encounter Ready For You records to enhance encounter performance.")
    }

}

System_Ext(npmpackages, "Miles Technologies NPM Packages", "Internally build Front end packages")
System_Ext(nugetpackages, "Miles Technologies Nuget Packages", "Internally build Back end packages")
System_Ext(medicaidFTP, "Government FTP", "Drops Medicaid Reports into FTP for State of Ohio Medicaid (Completely Manual)")

Rel(HCPCAdmin, BreckenridgeCoreAdminPortal, "peform user management")
Rel(SchoolAdmin, BreckenridgeCoreSchoolPortal, "peform school related information management")
Rel(Providers, BreckenridgeCoreProviderPortal, "perform encounters")

Rel(BreckenridgeCoreAdminPortal, api, "requests from the Admin Portal")
Rel(BreckenridgeCoreSchoolPortal, api, "requests from the School Portal")
Rel(BreckenridgeCoreProviderPortal, api, "requests from the Provider Portal")

Rel(api, servicelayer, "perform business Logic")
Rel(servicelayer, breckmodellayer, "model representation of DB")
Rel_Neighbor(ConsoleJobs, servicelayer, "uses")




Rel(breckmodellayer, breckdb, "uses db")
Rel(BreckenridgeCoreAdminPortal, npmpackages, "provide shared front end logic")
Rel(BreckenridgeCoreSchoolPortal, npmpackages, "provide shared front end logic")
Rel(BreckenridgeCoreProviderPortal, npmpackages, "provide shared front end logic")
Rel(BillingSchedulesJob, medicaidFTP, "receives")
Rel(api, nugetpackages,  "provide shared back end logic")
Rel(CoreApplication, nugetpackages,  "provide shared back end logic")
@enduml
