@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

'LAYOUT_LEFT_RIGHT
LAYOUT_WITH_LEGEND

title Container-Diagram-for-Advanced Reporting

System_Ext(breck, "Edudoc Implementation", "The custom application built on the Edudoc platform.")

System_Ext(nuget, "Edudoc Nuget Packages", "Internally build Nuget packages for backend logic.")
System_Ext(npm, "Edudoc Npm Packages", "Internally build NPM packages for our UI layer logic.")

System_Boundary(SB1, "Reporting Packages"){
    Container_Boundary(C1, "Reporting"){ 
        Container(api, "Reporting API", ".Net Standard 2.0", "Package that handles API routing logic.")
        Container(model, "Reporting Model", ".Net Standard 2.0", "Package that handles Model routing logic.")
        Container(servicelayer, "Reporting Service", ".Net Standard 2.0", "Package that handles Service routing logic.")
        Container(fe, "Advanced Reporting UI", "Angular 4", "Package that handles front end views and logic.")
    }
}


Rel(breck, api, "Uses", "HTTP")
Rel(breck, fe, "Uses")
Rel(fe, api, "Uses", "HTTP")
Rel(servicelayer, model, "Uses")
Rel(api, model, "Uses")
Rel(api, nuget, "Uses")
Rel(model, nuget, "Uses")
Rel(servicelayer, nuget, "Uses")
Rel(fe, npm, "Uses")

@enduml