import { IEntity, IDocument } from './base';

import { IActivitySummaryDistrict } from './activity-summary-district';
import { IAdminSchoolDistrict } from './admin-school-district';
import { IAnnualEntry } from './annual-entry';
import { IBillingScheduleDistrict } from './billing-schedule-district';
import { IClaimsDistrict } from './claims-district';
import { IContact } from './contact';
import { IDistrictProgressReportDate } from './district-progress-report-date';
import { IEncounterIdentifier } from './encounter-identifier';
import { IEscSchoolDistrict } from './esc-school-district';
import { IMessage } from './message';
import { IMessageDocument } from './message-document';
import { IMessageLink } from './message-link';
import { IPendingReferral } from './pending-referral';
import { IProviderCaseUpload } from './provider-case-upload';
import { IProviderCaseUploadDocument } from './provider-case-upload-document';
import { IProviderEscSchoolDistrict } from './provider-esc-school-district';
import { IRosterValidationDistrict } from './roster-validation-district';
import { ISchoolDistrictProviderCaseNote } from './school-district-provider-case-note';
import { ISchoolDistrictRoster } from './school-district-roster';
import { ISchoolDistrictRosterDocument } from './school-district-roster-document';
import { ISchoolDistrictsAccountAssistant } from './school-districts-account-assistant';
import { ISchoolDistrictsFinancialRep } from './school-districts-financial-rep';
import { ISchoolDistrictsSchool } from './school-districts-school';
import { IStudent } from './student';
import { IStudentDistrictWithdrawal } from './student-district-withdrawal';
import { IUnmatchedClaimRespons } from './unmatched-claim-respons';
import { IUser } from './user';
import { IVoucher } from './voucher';
import { IAddress } from './address';

export interface ISchoolDistrict extends IEntity {
    Name: string;
    Code: string;
    EinNumber: string;
    IrnNumber: string;
    NpiNumber: string;
    ProviderNumber: string;
    BecameTradingPartnerDate?: Date;
    BecameClientDate?: Date;
    RevalidationDate?: Date;
    ValidationExpirationDate?: Date;
    ProgressReports: boolean;
    ProgressReportsSent?: Date;
    RequireNotesForAllEncountersSent: boolean;
    NotesRequiredDate?: Date;
    Notes?: string;
    CreatedById: number;
    ModifiedById?: number;
    DateCreated?: Date;
    DateModified?: Date;
    UseDisabilityCodes: boolean;
    Archived: boolean;
    AddressId?: number;
    AccountManagerId?: number;
    AccountAssistantId?: number;
    TreasurerId?: number;
    SpecialEducationDirectorId?: number;
    MerId?: number;
    ActiveStatus: boolean;
    CaseNotesRequired: boolean;
    IepDatesRequired: boolean;

    // reverse nav
    ActivitySummaryDistricts?: IActivitySummaryDistrict[];
    AdminSchoolDistricts?: IAdminSchoolDistrict[];
    AnnualEntries?: IAnnualEntry[];
    BillingScheduleDistricts?: IBillingScheduleDistrict[];
    ClaimsDistricts?: IClaimsDistrict[];
    Contacts?: IContact[];
    DistrictProgressReportDates?: IDistrictProgressReportDate[];
    EncounterIdentifiers?: IEncounterIdentifier[];
    EscSchoolDistricts?: IEscSchoolDistrict[];
    Messages?: IMessage[];
    MessageDocuments?: IMessageDocument[];
    MessageLinks?: IMessageLink[];
    PendingReferrals?: IPendingReferral[];
    ProviderCaseUploads?: IProviderCaseUpload[];
    ProviderCaseUploadDocuments?: IProviderCaseUploadDocument[];
    ProviderEscSchoolDistricts?: IProviderEscSchoolDistrict[];
    RosterValidationDistricts?: IRosterValidationDistrict[];
    SchoolDistrictProviderCaseNotes?: ISchoolDistrictProviderCaseNote[];
    SchoolDistrictRosters?: ISchoolDistrictRoster[];
    SchoolDistrictRosterDocuments?: ISchoolDistrictRosterDocument[];
    SchoolDistrictsAccountAssistants?: ISchoolDistrictsAccountAssistant[];
    SchoolDistrictsFinancialReps?: ISchoolDistrictsFinancialRep[];
    SchoolDistrictsSchools?: ISchoolDistrictsSchool[];
    Students?: IStudent[];
    StudentDistrictWithdrawals?: IStudentDistrictWithdrawal[];
    UnmatchedClaimRespons?: IUnmatchedClaimRespons[];
    Users_DistrictAdminId?: IUser[];
    Users_SchoolDistrictId?: IUser[];
    Vouchers?: IVoucher[];

    // foreign keys
    Address?: IAddress;
    SpecialEducationDirector?: IContact;
    Treasurer?: IContact;
    MerFile?: IDocument;
    AccountAssistant?: IUser;
    AccountManager?: IUser;
    CreatedBy?: IUser;
    ModifiedBy?: IUser;
}
