import { IEntity, IVersionable, IDocument } from './base';

import { IActivitySummary } from './activity-summary';
import { IActivitySummaryDistrict } from './activity-summary-district';
import { IActivitySummaryProvider } from './activity-summary-provider';
import { IActivitySummaryServiceArea } from './activity-summary-service-area';
import { IAdminSchoolDistrict } from './admin-school-district';
import { IBillingFailure } from './billing-failure';
import { IBillingFile } from './billing-file';
import { IBillingResponseFile } from './billing-response-file';
import { IBillingSchedule } from './billing-schedule';
import { IBillingScheduleAdminNotification } from './billing-schedule-admin-notification';
import { IBillingScheduleDistrict } from './billing-schedule-district';
import { IBillingScheduleExcludedCptCode } from './billing-schedule-excluded-cpt-code';
import { IBillingScheduleExcludedProvider } from './billing-schedule-excluded-provider';
import { IBillingScheduleExcludedServiceCode } from './billing-schedule-excluded-service-code';
import { ICaseLoad } from './case-load';
import { ICaseLoadCptCode } from './case-load-cpt-code';
import { ICaseLoadGoal } from './case-load-goal';
import { ICaseLoadMethod } from './case-load-method';
import { ICaseLoadScript } from './case-load-script';
import { ICaseLoadScriptGoal } from './case-load-script-goal';
import { IContact } from './contact';
import { ICptCode } from './cpt-code';
import { ICptCodeAssocation } from './cpt-code-assocation';
import { IDiagnosisCode } from './diagnosis-code';
import { IDiagnosisCodeAssociation } from './diagnosis-code-association';
import { IEdiErrorCode } from './edi-error-code';
import { IEdiErrorCodeAdminNotification } from './edi-error-code-admin-notification';
import { IEncounter } from './encounter';
import { IEncounterReasonForReturn } from './encounter-reason-for-return';
import { IEncounterStudent } from './encounter-student';
import { IEncounterStudentCptCode } from './encounter-student-cpt-code';
import { IEncounterStudentGoal } from './encounter-student-goal';
import { IEncounterStudentMethod } from './encounter-student-method';
import { IEncounterStudentStatus } from './encounter-student-status';
import { IEsc } from './esc';
import { IEscSchoolDistrict } from './esc-school-district';
import { IEvaluationTypesDiagnosisCode } from './evaluation-types-diagnosis-code';
import { IGoal } from './goal';
import { IIepService } from './iep-service';
import { IImpersonationLog } from './impersonation-log';
import { IJobsAudit } from './jobs-audit';
import { IMergedStudent } from './merged-student';
import { IMessage } from './message';
import { IMessageDocument } from './message-document';
import { IMessageLink } from './message-link';
import { IPendingReferralReportJobRun } from './pending-referral-report-job-run';
import { IProgressReport } from './progress-report';
import { IProvider } from './provider';
import { IProviderCaseUpload } from './provider-case-upload';
import { IProviderCaseUploadDocument } from './provider-case-upload-document';
import { IProviderEscAssignment } from './provider-esc-assignment';
import { IProviderLicens } from './provider-licens';
import { IProviderOdeCertification } from './provider-ode-certification';
import { IProviderStudent } from './provider-student';
import { IProviderStudentSupervisor } from './provider-student-supervisor';
import { IProviderTitle } from './provider-title';
import { IProviderTraining } from './provider-training';
import { IReadMessage } from './read-message';
import { IRosterValidationFile } from './roster-validation-file';
import { IRosterValidationResponseFile } from './roster-validation-response-file';
import { ISchool } from './school';
import { ISchoolDistrict } from './school-district';
import { ISchoolDistrictRoster } from './school-district-roster';
import { ISchoolDistrictRosterDocument } from './school-district-roster-document';
import { ISchoolDistrictsAccountAssistant } from './school-districts-account-assistant';
import { ISchoolDistrictsFinancialRep } from './school-districts-financial-rep';
import { ISchoolDistrictsSchool } from './school-districts-school';
import { IServiceOutcome } from './service-outcome';
import { IServiceUnitRule } from './service-unit-rule';
import { IServiceUnitTimeSegment } from './service-unit-time-segment';
import { IStudent } from './student';
import { IStudentDisabilityCode } from './student-disability-code';
import { IStudentDistrictWithdrawal } from './student-district-withdrawal';
import { IStudentParentalConsent } from './student-parental-consent';
import { IStudentTherapy } from './student-therapy';
import { IStudentTherapySchedule } from './student-therapy-schedule';
import { ISupervisorProviderStudentReferalSignOff } from './supervisor-provider-student-referal-sign-off';
import { ITherapyCaseNote } from './therapy-case-note';
import { ITherapyGroup } from './therapy-group';
import { IUserPhone } from './user-phone';
import { IUserRole } from './user-role';
import { IVoucherBillingResponseFile } from './voucher-billing-response-file';
import { IAddress } from './address';
import { IAuthUser } from './auth-user';
import { IImage } from './image';

export interface IUser extends IEntity, IVersionable {
    FirstName: string;
    LastName: string;
    Email: string;
    AuthUserId: number;
    ImageId?: number;
    AddressId?: number;
    SchoolDistrictId?: number;
    CreatedById?: number;
    ModifiedById?: number;
    DateCreated?: Date;
    DateModified?: Date;
    Archived: boolean;

    // reverse nav
    ActivitySummaries?: IActivitySummary[];
    ActivitySummaryDistricts?: IActivitySummaryDistrict[];
    ActivitySummaryProviders?: IActivitySummaryProvider[];
    ActivitySummaryServiceAreas?: IActivitySummaryServiceArea[];
    AdminSchoolDistricts_AdminId?: IAdminSchoolDistrict[];
    AdminSchoolDistricts_CreatedById?: IAdminSchoolDistrict[];
    AdminSchoolDistricts_ModifiedById?: IAdminSchoolDistrict[];
    BillingFailures?: IBillingFailure[];
    BillingFiles?: IBillingFile[];
    BillingResponseFiles?: IBillingResponseFile[];
    BillingSchedules_CreatedById?: IBillingSchedule[];
    BillingSchedules_ModifiedById?: IBillingSchedule[];
    BillingScheduleAdminNotifications_AdminId?: IBillingScheduleAdminNotification[];
    BillingScheduleAdminNotifications_CreatedById?: IBillingScheduleAdminNotification[];
    BillingScheduleDistricts?: IBillingScheduleDistrict[];
    BillingScheduleExcludedCptCodes?: IBillingScheduleExcludedCptCode[];
    BillingScheduleExcludedProviders?: IBillingScheduleExcludedProvider[];
    BillingScheduleExcludedServiceCodes?: IBillingScheduleExcludedServiceCode[];
    CaseLoads_CreatedById?: ICaseLoad[];
    CaseLoads_ModifiedById?: ICaseLoad[];
    CaseLoadCptCodes_CreatedById?: ICaseLoadCptCode[];
    CaseLoadCptCodes_ModifiedById?: ICaseLoadCptCode[];
    CaseLoadGoals_CreatedById?: ICaseLoadGoal[];
    CaseLoadGoals_ModifiedById?: ICaseLoadGoal[];
    CaseLoadMethods_CreatedById?: ICaseLoadMethod[];
    CaseLoadMethods_ModifiedById?: ICaseLoadMethod[];
    CaseLoadScripts_ModifiedById?: ICaseLoadScript[];
    CaseLoadScripts_UploadedById?: ICaseLoadScript[];
    CaseLoadScriptGoals_CreatedById?: ICaseLoadScriptGoal[];
    CaseLoadScriptGoals_ModifiedById?: ICaseLoadScriptGoal[];
    Contacts_CreatedById?: IContact[];
    Contacts_ModifiedById?: IContact[];
    CptCodes_CreatedById?: ICptCode[];
    CptCodes_ModifiedById?: ICptCode[];
    CptCodeAssocations_CreatedById?: ICptCodeAssocation[];
    CptCodeAssocations_ModifiedById?: ICptCodeAssocation[];
    DiagnosisCodes_CreatedById?: IDiagnosisCode[];
    DiagnosisCodes_ModifiedById?: IDiagnosisCode[];
    DiagnosisCodeAssociations_CreatedById?: IDiagnosisCodeAssociation[];
    DiagnosisCodeAssociations_ModifiedById?: IDiagnosisCodeAssociation[];
    Documents?: IDocument[];
    Documents_UploadedBy?: IDocument[];
    EdiErrorCodes_CreatedById?: IEdiErrorCode[];
    EdiErrorCodes_ModifiedById?: IEdiErrorCode[];
    EdiErrorCodeAdminNotifications?: IEdiErrorCodeAdminNotification[];
    Encounters_CreatedById?: IEncounter[];
    Encounters_ModifiedById?: IEncounter[];
    EncounterReasonForReturns_CreatedById?: IEncounterReasonForReturn[];
    EncounterReasonForReturns_HpcUserId?: IEncounterReasonForReturn[];
    EncounterReasonForReturns_ModifiedById?: IEncounterReasonForReturn[];
    EncounterStudents_CreatedById?: IEncounterStudent[];
    EncounterStudents_ESignedById?: IEncounterStudent[];
    EncounterStudents_ModifiedById?: IEncounterStudent[];
    EncounterStudents_SupervisorESignedById?: IEncounterStudent[];
    EncounterStudentCptCodes_CreatedById?: IEncounterStudentCptCode[];
    EncounterStudentCptCodes_ModifiedById?: IEncounterStudentCptCode[];
    EncounterStudentGoals_CreatedById?: IEncounterStudentGoal[];
    EncounterStudentGoals_ModifiedById?: IEncounterStudentGoal[];
    EncounterStudentMethods_CreatedById?: IEncounterStudentMethod[];
    EncounterStudentMethods_ModifiedById?: IEncounterStudentMethod[];
    EncounterStudentStatus?: IEncounterStudentStatus[];
    Escs_CreatedById?: IEsc[];
    Escs_ModifiedById?: IEsc[];
    EscSchoolDistricts_CreatedById?: IEscSchoolDistrict[];
    EscSchoolDistricts_ModifiedById?: IEscSchoolDistrict[];
    EvaluationTypesDiagnosisCodes_CreatedById?: IEvaluationTypesDiagnosisCode[];
    EvaluationTypesDiagnosisCodes_ModifiedById?: IEvaluationTypesDiagnosisCode[];
    Goals_CreatedById?: IGoal[];
    Goals_ModifiedById?: IGoal[];
    IepServices_CreatedById?: IIepService[];
    IepServices_ModifiedById?: IIepService[];
    ImpersonationLogs?: IImpersonationLog[];
    JobsAudits?: IJobsAudit[];
    MergedStudents?: IMergedStudent[];
    Messages_CreatedById?: IMessage[];
    Messages_ModifiedById?: IMessage[];
    MessageDocuments_CreatedById?: IMessageDocument[];
    MessageDocuments_ModifiedById?: IMessageDocument[];
    MessageLinks_CreatedById?: IMessageLink[];
    MessageLinks_ModifiedById?: IMessageLink[];
    PendingReferralReportJobRuns?: IPendingReferralReportJobRun[];
    ProgressReports_CreatedById?: IProgressReport[];
    ProgressReports_ESignedById?: IProgressReport[];
    ProgressReports_ModifiedById?: IProgressReport[];
    ProgressReports_SupervisorESignedById?: IProgressReport[];
    Providers_CreatedById?: IProvider[];
    Providers_ModifiedById?: IProvider[];
    Providers_ProviderUserId?: IProvider[];
    ProviderCaseUploads?: IProviderCaseUpload[];
    ProviderCaseUploadDocuments?: IProviderCaseUploadDocument[];
    ProviderEscAssignments_CreatedById?: IProviderEscAssignment[];
    ProviderEscAssignments_ModifiedById?: IProviderEscAssignment[];
    ProviderLicens?: IProviderLicens[];
    ProviderOdeCertifications?: IProviderOdeCertification[];
    ProviderStudents?: IProviderStudent[];
    ProviderStudentSupervisors_CreatedById?: IProviderStudentSupervisor[];
    ProviderStudentSupervisors_ModifiedById?: IProviderStudentSupervisor[];
    ProviderTitles_CreatedById?: IProviderTitle[];
    ProviderTitles_ModifiedById?: IProviderTitle[];
    ProviderTrainings?: IProviderTraining[];
    ReadMessages?: IReadMessage[];
    RosterValidationFiles?: IRosterValidationFile[];
    RosterValidationResponseFiles?: IRosterValidationResponseFile[];
    Schools_CreatedById?: ISchool[];
    Schools_ModifiedById?: ISchool[];
    SchoolDistricts_AccountAssistantId?: ISchoolDistrict[];
    SchoolDistricts_AccountManagerId?: ISchoolDistrict[];
    SchoolDistricts_CreatedById?: ISchoolDistrict[];
    SchoolDistricts_DistrictId?: ISchoolDistrict[];
    SchoolDistricts_ModifiedById?: ISchoolDistrict[];
    SchoolDistrictRosters?: ISchoolDistrictRoster[];
    SchoolDistrictRosterDocuments?: ISchoolDistrictRosterDocument[];
    SchoolDistrictsAccountAssistants?: ISchoolDistrictsAccountAssistant[];
    SchoolDistrictsFinancialReps?: ISchoolDistrictsFinancialRep[];
    SchoolDistrictsSchools_CreatedById?: ISchoolDistrictsSchool[];
    SchoolDistrictsSchools_ModifiedById?: ISchoolDistrictsSchool[];
    ServiceOutcomes_CreatedById?: IServiceOutcome[];
    ServiceOutcomes_ModifiedById?: IServiceOutcome[];
    ServiceUnitRules_CreatedById?: IServiceUnitRule[];
    ServiceUnitRules_ModifiedById?: IServiceUnitRule[];
    ServiceUnitTimeSegments_CreatedById?: IServiceUnitTimeSegment[];
    ServiceUnitTimeSegments_ModifiedById?: IServiceUnitTimeSegment[];
    Students_CreatedById?: IStudent[];
    Students_ModifiedById?: IStudent[];
    StudentDisabilityCodes_CreatedById?: IStudentDisabilityCode[];
    StudentDisabilityCodes_ModifiedById?: IStudentDisabilityCode[];
    StudentDistrictWithdrawals_CreatedById?: IStudentDistrictWithdrawal[];
    StudentDistrictWithdrawals_ModifiedById?: IStudentDistrictWithdrawal[];
    StudentParentalConsents_CreatedById?: IStudentParentalConsent[];
    StudentParentalConsents_ModifiedById?: IStudentParentalConsent[];
    StudentTherapies_CreatedById?: IStudentTherapy[];
    StudentTherapies_ModifiedById?: IStudentTherapy[];
    StudentTherapySchedules_CreatedById?: IStudentTherapySchedule[];
    StudentTherapySchedules_ModifiedById?: IStudentTherapySchedule[];
    SupervisorProviderStudentReferalSignOffs_CreatedById?: ISupervisorProviderStudentReferalSignOff[];
    SupervisorProviderStudentReferalSignOffs_ModifiedById?: ISupervisorProviderStudentReferalSignOff[];
    SupervisorProviderStudentReferalSignOffs_SignedOffById?: ISupervisorProviderStudentReferalSignOff[];
    TherapyCaseNotes?: ITherapyCaseNote[];
    TherapyGroups_CreatedById?: ITherapyGroup[];
    TherapyGroups_ModifiedById?: ITherapyGroup[];
    Users_CreatedById?: IUser[];
    Users_ModifiedById?: IUser[];
    UserPhones?: IUserPhone[];
    UserRoles_CreatedById?: IUserRole[];
    UserRoles_ModifiedById?: IUserRole[];
    VoucherBillingResponseFiles?: IVoucherBillingResponseFile[];

    // foreign keys
    Address?: IAddress;
    AuthUser?: IAuthUser;
    Image?: IImage;
    SchoolDistrict?: ISchoolDistrict;
    CreatedBy?: IUser;
    ModifiedBy?: IUser;
}
