CREATE TABLE [dbo].[StudentTherapies]
(
	[Id] INT NOT NULL IDENTITY, 
    [CaseLoadId] INT NOT NULL,
    [ProviderId] INT NULL,
    [EncounterLocationId] INT NOT NULL,
    [TherapyGroupId] INT NULL,
    [StartDate] DATETIME NOT NULL, 
    [EndDate] DATETIME NOT NULL, 
    [Monday] BIT NOT NULL DEFAULT(0), 
    [Tuesday]  BIT NOT NULL DEFAULT(0),
    [Wednesday]  BIT NOT NULL DEFAULT(0),
    [Thursday]  BIT NOT NULL DEFAULT(0),
    [Friday]  BIT NOT NULL DEFAULT(0),
    [SessionName] VARCHAR(50) NULL,
    [Archived]  BIT NOT NULL   DEFAULT 0,
    [CreatedById] INT NOT NULL DEFAULT 1, 
    [ModifiedById] INT NULL, 
    [DateCreated]  DATETIME NULL DEFAULT GETUTCDATE(),
    [DateModified] DATETIME NULL,
    CONSTRAINT [PK_StudentTherapies] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_StudentTherapies_CaseLoad] FOREIGN KEY (CaseLoadId) REFERENCES [dbo].[CaseLoads] ([Id]),
    CONSTRAINT [FK_StudentTherapies_Provider] FOREIGN KEY ([ProviderId]) REFERENCES [dbo].[Providers] ([Id]),
	CONSTRAINT [FK_StudentTherapies_EncounterLocation] FOREIGN KEY (EncounterLocationId) REFERENCES [dbo].[EncounterLocations] ([Id]),
	CONSTRAINT [FK_StudentTherapies_TherapyGroup] FOREIGN KEY (TherapyGroupId) REFERENCES [dbo].[TherapyGroups] ([Id]),
    CONSTRAINT [FK_StudentTherapies_CreatedBy] FOREIGN KEY (CreatedById) REFERENCES [dbo].[Users] ([Id]),
	CONSTRAINT [FK_StudentTherapies_ModifiedBy] FOREIGN KEY (ModifiedById) REFERENCES [dbo].[Users] ([Id]),
)
