import { ClaimTypes } from '@model/ClaimTypes';
import { ClaimValues } from '@mt-ng2/auth-module';
import { KeyboardKeys } from '@mt-ng2/keyboard-shortcuts-module';
import { NavSidebarRowItem, NavSidebarParentRowItem } from '@mt-ng2/nav-module';

// tslint:disable:object-literal-sort-keys
export const adminNavMenu: (NavSidebarRowItem | NavSidebarParentRowItem)[] = [
    new NavSidebarRowItem({
        content: 'My Profile',
        icon: 'fa fa-fw fa-address-card',
        link: '/admin/my-profile',
    }),
    new NavSidebarParentRowItem({
        children: [
            new NavSidebarRowItem({
                addLink: '/admin/users/add',
                addClaimType: ClaimTypes.Users,
                addClaimValues: [ClaimValues.FullAccess],
                claimType: ClaimTypes.Users,
                content: 'Users',
                icon: 'fa fa-fw fa-user',
                link: '/admin/users',
                shortcut: {
                    keyBinding: [KeyboardKeys.Alt, KeyboardKeys.Shift, 'U'],
                    description: 'go to Users',
                },
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.ManagedListItems,
                claimValues: [ClaimValues.FullAccess],
                content: 'Manage List Items',
                icon: 'fa fa-fw fa-columns',
                link: '/admin/managed-list-items',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.ProviderAcknowledgements,
                claimValues: [ClaimValues.FullAccess],
                content: 'Provider Attestations',
                icon: 'fa fa-fw fa-handshake-o',
                link: '/admin/attestations',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.AppSettings,
                claimValues: [ClaimValues.FullAccess],
                content: 'Evaluation Types',
                icon: 'fa fa-fw fa-check',
                link: '/admin/evaluation-types',
            }),
            new NavSidebarRowItem({
                addLink: '/admin/cpt-codes/add',
                addClaimType: ClaimTypes.CPTCodes,
                addClaimValues: [ClaimValues.FullAccess],
                claimType: ClaimTypes.CPTCodes,
                claimValues: [ClaimValues.FullAccess],
                content: 'CPT Codes',
                icon: 'fa fa-fw fa-stethoscope',
                link: '/admin/cpt-codes',
            }),
            new NavSidebarRowItem({
                addLink: '/admin/goals/add',
                addClaimType: ClaimTypes.ProviderGoals,
                addClaimValues: [ClaimValues.FullAccess],
                claimType: ClaimTypes.ProviderGoals,
                claimValues: [ClaimValues.FullAccess],
                content: 'Goals/Progress',
                icon: 'fa fa-fw fa-bullseye',
                link: '/admin/goals',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.ProviderGoals,
                claimValues: [ClaimValues.FullAccess],
                content: 'Service Outcome',
                icon: 'fa fa-fw fa-bullseye',
                link: '/admin/service-outcomes',
            }),
            new NavSidebarRowItem({
                addLink: '/admin/provider-titles/add',
                addClaimType: ClaimTypes.ProviderTitles,
                addClaimValues: [ClaimValues.FullAccess],
                claimType: ClaimTypes.ProviderTitles,
                claimValues: [ClaimValues.FullAccess],
                content: 'Provider Title',
                icon: 'fa fa-fw fa-vcard',
                link: '/admin/provider-titles',
            }),
            new NavSidebarRowItem({
                addLink: '/admin/diagnosis-codes/add',
                addClaimType: ClaimTypes.DiagnosisCodes,
                addClaimValues: [ClaimValues.FullAccess],
                claimType: ClaimTypes.DiagnosisCodes,
                content: 'Diagnosis Codes',
                icon: 'fa fa-fw fa-heartbeat',
                link: '/admin/diagnosis-codes',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.ReturnReasons,
                content: 'My Reasons For Return',
                icon: 'fa fa-fw fa-eject',
                link: '/admin/my-reasons-for-return',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.AppSettings,
                content: 'Edi Error Codes',
                icon: 'fa fa-fw fa-exclamation-triangle',
                link: '/admin/edi-response-error-codes',
            }),
        ],
        claimType: ClaimTypes.AppSettings,
        content: 'Administration',
        expanded: false,
        icon: 'fa fa-fw fa-university',
        settingsLink: '/admin/settings',
        settingsClaimType: ClaimTypes.AppSettings,
    }),
    new NavSidebarParentRowItem({
        children: [
            new NavSidebarRowItem({
                addClaimType: ClaimTypes.Documents,
                addClaimValues: [ClaimValues.FullAccess],
                claimType: ClaimTypes.Documents,
                content: 'Documents',
                icon: 'fa fa-fw fa-file',
                link: '/admin/message-documents',
            }),
            new NavSidebarRowItem({
                addClaimType: ClaimTypes.Links,
                addClaimValues: [ClaimValues.FullAccess],
                claimType: ClaimTypes.Links,
                content: 'Links',
                icon: 'fa fa-fw fa-link',
                link: '/admin/message-links',
            }),
            new NavSidebarRowItem({
                addClaimType: ClaimTypes.MessageMaintenance,
                addClaimValues: [ClaimValues.FullAccess],
                claimType: ClaimTypes.MessageMaintenance,
                content: 'Messages',
                icon: 'fa fa-fw fa-envelope',
                link: '/admin/messages',
            }),
        ],
        claimType: ClaimTypes.MessageMaintenance,
        content: 'Message',
        expanded: false,
        icon: 'fa fa-fw fa-envelope',
    }),
    new NavSidebarParentRowItem({
        children: [
            new NavSidebarRowItem({
                addClaimType: ClaimTypes.CPTCodes,
                addClaimValues: [ClaimValues.FullAccess],
                claimType: ClaimTypes.CPTCodes,
                content: 'Service Unit Rules',
                icon: 'fa fa-fw fa-tasks',
                link: '/admin/service-unit-rules',
            }),
        ],
        claimType: ClaimTypes.CPTCodes,
        content: 'Service Unit Rules',
        expanded: false,
        icon: 'fa fa-fw fa-tasks',
    }),
    new NavSidebarRowItem({
        addLink: '/admin/escs/add',
        addClaimType: ClaimTypes.ESCs,
        addClaimValues: [ClaimValues.FullAccess],
        claimType: ClaimTypes.ESCs,
        content: 'ESCs',
        icon: 'fa fa-fw fa-building',
        link: '/admin/escs',
    }),
    new NavSidebarParentRowItem({
        children: [
            new NavSidebarRowItem({
                addLink: '/admin/school-districts/add',
                addClaimType: ClaimTypes.SchoolDistricts,
                addClaimValues: [ClaimValues.FullAccess],
                claimType: ClaimTypes.SchoolDistricts,
                content: 'School Districts',
                icon: 'fa fa-fw fa-book',
                link: '/admin/school-districts',
            }),
            new NavSidebarRowItem({
                addLink: '/admin/school-district-admins/add',
                addClaimType: ClaimTypes.Users,
                addClaimValues: [ClaimValues.FullAccess],
                claimType: ClaimTypes.Users,
                content: 'District Admins',
                icon: 'fa fa-fw fa-user',
                link: '/admin/school-district-admins',
            }),
        ],
        claimType: ClaimTypes.SchoolDistricts,
        content: 'District Management',
        expanded: false,
        icon: 'fa fa-fw fa-book',
    }),
    new NavSidebarParentRowItem({
        children: [
            new NavSidebarRowItem({
                addLink: '/admin/providers/add',
                addClaimType: ClaimTypes.ProviderMaintenance,
                addClaimValues: [ClaimValues.FullAccess],
                claimType: ClaimTypes.ProviderMaintenance,
                content: 'Providers',
                icon: 'fa fa-fw fa-medkit',
                link: '/admin/providers',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.ProviderMaintenance,
                content: 'Medicaid Status',
                icon: 'fa fa-fw fa-medkit',
                link: '/admin/provider-medicaid-status',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.ProviderMaintenance,
                content: 'Provider Trainings',
                icon: 'fa fa-fw fa-book',
                link: '/admin/provider-trainings',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.ProviderMaintenance,
                claimValues: [ClaimValues.FullAccess],
                content: 'Training Documents',
                icon: 'fa fa-fw fa-book',
                link: '/admin/provider-training-documents',
            }),
        ],
        claimType: ClaimTypes.Encounters,
        content: 'Providers',
        expanded: false,
        icon: 'fa fa-fw fa-medkit',
    }),
    new NavSidebarParentRowItem({
        children: [
            new NavSidebarRowItem({
                claimType: ClaimTypes.ReviewEncounters,
                content: 'Revise Encounters',
                icon: 'fa fa-fw fa-book',
                link: '/admin/encounters',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.ReviewEncounters,
                content: 'Encounters AUP Audit',
                icon: 'fa fa-fw fa-book',
                link: '/admin/encounters-aup-audit',
            }),
        ],
        claimType: ClaimTypes.Encounters,
        content: 'Encounters',
        expanded: false,
        icon: 'fa fa-fw fa-book',
    }),
    new NavSidebarParentRowItem({
        children: [
            new NavSidebarRowItem({
                addLink: '/admin/students/add',
                addClaimType: ClaimTypes.Students,
                addClaimValues: [ClaimValues.FullAccess],
                claimType: ClaimTypes.ReviewStudent,
                content: 'Review Students',
                icon: 'fa fa-fw fa-child',
                link: '/admin/students',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.Students,
                content: 'Missing Student Addresses',
                icon: 'fa fa-fw fa-child',
                link: '/admin/student-missing-addresses',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.Students,
                content: 'Students Missing Data',
                icon: 'fa fa-fw fa-child',
                link: '/admin/students-no-medicaid',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.ReviewParentConsent,
                content: 'Review Parental Consents',
                icon: 'fa fa-fw fa-book',
                link: '/admin/student-parental-consents-district',
            }),
        ],
        claimType: ClaimTypes.Students,
        content: 'Students',
        expanded: false,
        icon: 'fa fa-fw fa-child',
    }),
    new NavSidebarParentRowItem({
        children: [
            new NavSidebarRowItem({
                addLink: '/admin/billing-schedules/add',
                addClaimType: ClaimTypes.ReviewSchedules,
                addClaimValues: [ClaimValues.FullAccess],
                claimType: ClaimTypes.ReviewSchedules,
                content: 'Review Schedules',
                icon: 'fa fa-fw fa-book',
                link: '/admin/billing-schedules',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.ReviewFiles,
                content: 'Review Files',
                icon: 'fa fa-fw fa-book',
                link: '/admin/billing-files',
            }),
            new NavSidebarRowItem({
                // TODO SD: claimType: ClaimTypes.BillingReversals,
                claimType: ClaimTypes.ReviewEncounters,
                content: 'Billing Reversals',
                icon: 'fa fa-fw fa-book',
                link: '/admin/reversals',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.RejectedEncounters,
                content: 'Denied Claims',
                icon: 'fa fa-fw fa-book',
                link: '/admin/rejected-encounters',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.RejectedEncounters,
                content: 'Ineligible Encounters',
                icon: 'fa fa-fw fa-book',
                link: '/admin/ineligible-encounters',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.Vouchers,
                content: 'Vouchers',
                icon: 'fa fa-fw fa-book',
                link: '/admin/vouchers',
            }),
            new NavSidebarRowItem({
                addLink: '/admin/annual-entries/add',
                addClaimType: ClaimTypes.BillingSchedules,
                addClaimValues: [ClaimValues.FullAccess],
                claimType: ClaimTypes.BillingSchedules,
                content: 'Annual Entry',
                icon: 'fa fa-fw fa-book',
                link: '/admin/annual-entries',
            }),
        ],
        claimType: ClaimTypes.BillingSchedules,
        content: 'Billing Schedules',
        expanded: false,
        icon: 'fa fa-fw fa-book',
    }),
    new NavSidebarParentRowItem({
        children: [
            new NavSidebarRowItem({
                claimType: ClaimTypes.MedMatch,
                content: 'Review Files',
                icon: 'fa fa-fw fa-book',
                link: '/admin/roster-validation-files',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.MedMatch,
                content: '271 Uploads',
                icon: 'fa fa-fw fa-book',
                link: '/admin/271-uploads',
            }),
        ],
        claimType: ClaimTypes.MedMatch,
        content: 'MedMatch',
        expanded: false,
        icon: 'fa fa-fw fa-book',
    }),
    new NavSidebarParentRowItem({
        children: [
            new NavSidebarRowItem({
                claimType: ClaimTypes.Encounters,
                content: 'Pending Referral Report',
                icon: 'fa fa-fw fa-book',
                link: '/admin/pending-referral-report',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.Encounters,
                content: 'Completed Referral Report',
                icon: 'fa fa-fw fa-book',
                link: '/admin/completed-referral-report',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.DistrictActivitySummaryByServiceArea,
                content: 'Completed Activity Report',
                icon: 'fa fa-fw fa-book',
                link: '/admin/completed-activity-report',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.DistrictActivitySummaryByServiceArea,
                content: 'Summary of Outstanding Documentation',
                icon: 'fa fa-fw fa-book',
                link: '/admin/summary-report',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.DistrictActivitySummaryByServiceArea,
                content: 'Audits',
                icon: 'fa fa-fw fa-book',
                link: '/admin/audits',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.IneligibleClaims,
                content: 'Ineligible Claims',
                icon: 'fa fa-fw fa-book',
                link: '/admin/ineligible-claims',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.FiscalRevenue,
                content: 'Fiscal Revenue Report',
                icon: 'fa fa-fw fa-book',
                link: '/admin/fiscal-revenue-report',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.FiscalSummary,
                content: 'Fiscal Summary Report',
                icon: 'fa fa-fw fa-book',
                link: '/admin/fiscal-summary-report',
            }),
            new NavSidebarRowItem({
                claimType: ClaimTypes.FiscalSummary,
                content: '90 Day Progress Reports',
                icon: 'fa fa-fw fa-book',
                link: '/admin/progress-reports',
            }),
        ],
        claimType: ClaimTypes.Encounters,
        content: 'Reports',
        expanded: false,
        icon: 'fa fa-fw fa-book',
    }),
    new NavSidebarParentRowItem({
        children: [
            new NavSidebarRowItem({
                claimType: ClaimTypes.Encounters,
                claimValues: [ClaimValues.ReadOnly, ClaimValues.FullAccess],
                content: 'Encounters',
                icon: 'fa fa-fw fa-file-text',
                link: '/admin/data-import',
            }),
            // You can add more import types here in the future
        ],
        claimType: ClaimTypes.Encounters,
        content: 'Data Import',
        expanded: false,
        icon: 'fa fa-fw fa-upload',
    }),
    new NavSidebarRowItem({
        content: 'Sign Out',
        icon: 'fa fa-fw fa-sign-out',
        link: '/sign-out',
    }),
];
// tslint:enable:object-literal-sort-keys
