// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // AdminSchoolDistricts
    [Table("AdminSchoolDistricts", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class AdminSchoolDistrict: IEntity
    {
        // AdminSchoolDistrict
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_AdminSchoolDistrict", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"AdminId", Order = 2, TypeName = "int")]
        [Display(Name = "Admin ID")]
        public int AdminId { get; set; } // AdminId

        [Column(@"SchoolDistrictId", Order = 3, TypeName = "int")]
        [Display(Name = "School district ID")]
        public int SchoolDistrictId { get; set; } // SchoolDistrictId

        [Column(@"CreatedById", Order = 4, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"ModifiedById", Order = 5, TypeName = "int")]
        [Display(Name = "Modified by ID")]
        public int? ModifiedById { get; set; } // ModifiedById

        [Column(@"DateCreated", Order = 6, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        [Column(@"DateModified", Order = 7, TypeName = "datetime")]
        [Display(Name = "Date modified")]
        public System.DateTime? DateModified { get; set; } // DateModified

        [Column(@"Archived", Order = 8, TypeName = "bit")]
        [Display(Name = "Archived")]
        public bool Archived { get; set; } // Archived

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [AdminSchoolDistricts].([AdminId]) (FK_AdminSchoolDistrict_Admin)
        /// </summary>
        [InverseProperty("AdminSchoolDistricts_AdminId")]
        [ForeignKey("AdminId")] public User Admin { get; set; } // FK_AdminSchoolDistrict_Admin

        /// <summary>
        /// Parent User pointed by [AdminSchoolDistricts].([CreatedById]) (FK_AdminSchoolDistrict_CreatedBy)
        /// </summary>
        [InverseProperty("AdminSchoolDistricts_CreatedById")]
        [ForeignKey("CreatedById")] public User CreatedBy { get; set; } // FK_AdminSchoolDistrict_CreatedBy

        /// <summary>
        /// Parent User pointed by [AdminSchoolDistricts].([ModifiedById]) (FK_AdminSchoolDistrict_ModifiedBy)
        /// </summary>
        [InverseProperty("AdminSchoolDistricts_ModifiedById")]
        [ForeignKey("ModifiedById")] public User ModifiedBy { get; set; } // FK_AdminSchoolDistrict_ModifiedBy

        /// <summary>
        /// Parent SchoolDistrict pointed by [AdminSchoolDistricts].([SchoolDistrictId]) (FK_AdminSchoolDistrict_SchoolDistrict)
        /// </summary>
        [InverseProperty("AdminSchoolDistricts")]
        [ForeignKey("SchoolDistrictId")] public SchoolDistrict SchoolDistrict { get; set; } // FK_AdminSchoolDistrict_SchoolDistrict

        public AdminSchoolDistrict()
        {
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            Archived = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
