// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // AnnualEntries
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class AnnualEntryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AnnualEntry>
    {
        public AnnualEntryConfiguration()
            : this("dbo")
        {
        }

        public AnnualEntryConfiguration(string schema)
        {
            Property(x => x.Year).IsUnicode(false);
            Property(x => x.AllowableCosts).IsUnicode(false);
            Property(x => x.InterimPayments).IsUnicode(false);
            Property(x => x.SettlementAmount).IsUnicode(false);
            Property(x => x.Mer).IsOptional().IsUnicode(false);
            Property(x => x.Rmts).IsOptional().IsUnicode(false);

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
