// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // BillingResponseFiles
    [Table("BillingResponseFiles", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class BillingResponseFile: IEntity, IBasicNameEntity
    {
        // BillingResponseFile
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_BillingResponseFiles", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"Name", Order = 2, TypeName = "varchar")]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 200)

        [Column(@"DateUploaded", Order = 3, TypeName = "datetime")]
        [Display(Name = "Date uploaded")]
        public System.DateTime DateUploaded { get; set; } // DateUploaded

        [Column(@"DateProcessed", Order = 4, TypeName = "datetime")]
        [Display(Name = "Date processed")]
        public System.DateTime? DateProcessed { get; set; } // DateProcessed

        [Column(@"FilePath", Order = 5, TypeName = "varchar")]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "File path")]
        public string FilePath { get; set; } // FilePath (length: 200)

        [Column(@"UploadedById", Order = 6, TypeName = "int")]
        [Display(Name = "Uploaded by ID")]
        public int? UploadedById { get; set; } // UploadedById

        // Reverse navigation

        /// <summary>
        /// Child UnmatchedClaimDistricts where [UnmatchedClaimDistricts].[ResponseFileId] point to this entity (FK_UnmatchedClaimDistricts_ResponseFile)
        /// </summary>
        public System.Collections.Generic.ICollection<UnmatchedClaimDistrict> UnmatchedClaimDistricts { get; set; } // UnmatchedClaimDistricts.FK_UnmatchedClaimDistricts_ResponseFile
        /// <summary>
        /// Child UnmatchedClaimRespons where [UnmatchedClaimResponses].[ResponseFileId] point to this entity (FK_UnmatchedClaimResponses_ResponseFile)
        /// </summary>
        public System.Collections.Generic.ICollection<UnmatchedClaimRespons> UnmatchedClaimRespons { get; set; } // UnmatchedClaimResponses.FK_UnmatchedClaimResponses_ResponseFile
        /// <summary>
        /// Child VoucherBillingResponseFiles where [VoucherBillingResponseFiles].[BillingResponseFileId] point to this entity (FK_VoucherBillingResponseFiles_Students)
        /// </summary>
        public System.Collections.Generic.ICollection<VoucherBillingResponseFile> VoucherBillingResponseFiles { get; set; } // VoucherBillingResponseFiles.FK_VoucherBillingResponseFiles_Students

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [BillingResponseFiles].([UploadedById]) (FK_BillingResponseFiles_Users)
        /// </summary>
        [InverseProperty("BillingResponseFiles")]
        [ForeignKey("UploadedById")] public User User { get; set; } // FK_BillingResponseFiles_Users

        public BillingResponseFile()
        {
            DateUploaded = System.DateTime.UtcNow;
            VoucherBillingResponseFiles = new System.Collections.Generic.List<VoucherBillingResponseFile>();
            UnmatchedClaimDistricts = new System.Collections.Generic.List<UnmatchedClaimDistrict>();
            UnmatchedClaimRespons = new System.Collections.Generic.List<UnmatchedClaimRespons>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
