// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // BillingScheduleAdminNotifications
    [Table("BillingScheduleAdminNotifications", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class BillingScheduleAdminNotification: IEntity
    {
        // BillingScheduleAdminNotification
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_BillingScheduleAdminNotfications", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"AdminId", Order = 2, TypeName = "int")]
        [Display(Name = "Admin ID")]
        public int AdminId { get; set; } // AdminId

        [Column(@"BillingScheduleId", Order = 3, TypeName = "int")]
        [Display(Name = "Billing schedule ID")]
        public int BillingScheduleId { get; set; } // BillingScheduleId

        [Column(@"CreatedById", Order = 4, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"DateCreated", Order = 5, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [BillingScheduleAdminNotifications].([AdminId]) (FK_BillingScheduleAdminNotifications_Admin)
        /// </summary>
        [InverseProperty("BillingScheduleAdminNotifications_AdminId")]
        [ForeignKey("AdminId")] public User Admin { get; set; } // FK_BillingScheduleAdminNotifications_Admin

        /// <summary>
        /// Parent BillingSchedule pointed by [BillingScheduleAdminNotifications].([BillingScheduleId]) (FK_BillingScheduleAdminNotifications_BillingSchedule)
        /// </summary>
        [InverseProperty("BillingScheduleAdminNotifications")]
        [ForeignKey("BillingScheduleId")] public BillingSchedule BillingSchedule { get; set; } // FK_BillingScheduleAdminNotifications_BillingSchedule

        /// <summary>
        /// Parent User pointed by [BillingScheduleAdminNotifications].([CreatedById]) (FK_BillingScheduleAdminNotifications_CreatedBy)
        /// </summary>
        [InverseProperty("BillingScheduleAdminNotifications_CreatedById")]
        [ForeignKey("CreatedById")] public User CreatedBy { get; set; } // FK_BillingScheduleAdminNotifications_CreatedBy

        public BillingScheduleAdminNotification()
        {
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
