// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // BillingScheduleExcludedProviders
    [Table("BillingScheduleExcludedProviders", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class BillingScheduleExcludedProvider: IEntity
    {
        // BillingScheduleExcludedProvider
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_BillingScheduleExcludedProviders", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"ProviderId", Order = 2, TypeName = "int")]
        [Display(Name = "Provider ID")]
        public int ProviderId { get; set; } // ProviderId

        [Column(@"BillingScheduleId", Order = 3, TypeName = "int")]
        [Display(Name = "Billing schedule ID")]
        public int BillingScheduleId { get; set; } // BillingScheduleId

        [Column(@"CreatedById", Order = 4, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"DateCreated", Order = 5, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        // Foreign keys

        /// <summary>
        /// Parent BillingSchedule pointed by [BillingScheduleExcludedProviders].([BillingScheduleId]) (FK_BillingScheduleExcludedProviders_BillingSchedule)
        /// </summary>
        [InverseProperty("BillingScheduleExcludedProviders")]
        [ForeignKey("BillingScheduleId")] public BillingSchedule BillingSchedule { get; set; } // FK_BillingScheduleExcludedProviders_BillingSchedule

        /// <summary>
        /// Parent User pointed by [BillingScheduleExcludedProviders].([CreatedById]) (FK_BillingScheduleExcludedProviders_CreatedBy)
        /// </summary>
        [InverseProperty("BillingScheduleExcludedProviders")]
        [ForeignKey("CreatedById")] public User User { get; set; } // FK_BillingScheduleExcludedProviders_CreatedBy

        /// <summary>
        /// Parent Provider pointed by [BillingScheduleExcludedProviders].([ProviderId]) (FK_BillingScheduleExcludedProviders_Provider)
        /// </summary>
        [InverseProperty("BillingScheduleExcludedProviders")]
        [ForeignKey("ProviderId")] public Provider Provider { get; set; } // FK_BillingScheduleExcludedProviders_Provider

        public BillingScheduleExcludedProvider()
        {
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
