// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // BillingScheduleExcludedCptCodes
    [Table("BillingScheduleExcludedCptCodes", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class BillingScheduleExcludedCptCode: IEntity
    {
        // BillingScheduleExcludedCptCode
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_BillingScheduleExcludedCptCodes", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"CptCodeId", Order = 2, TypeName = "int")]
        [Display(Name = "Cpt code ID")]
        public int CptCodeId { get; set; } // CptCodeId

        [Column(@"BillingScheduleId", Order = 3, TypeName = "int")]
        [Display(Name = "Billing schedule ID")]
        public int BillingScheduleId { get; set; } // BillingScheduleId

        [Column(@"CreatedById", Order = 4, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"DateCreated", Order = 5, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        // Foreign keys

        /// <summary>
        /// Parent BillingSchedule pointed by [BillingScheduleExcludedCptCodes].([BillingScheduleId]) (FK_BillingScheduleExcludedCptCodes_BillingSchedule)
        /// </summary>
        [InverseProperty("BillingScheduleExcludedCptCodes")]
        [ForeignKey("BillingScheduleId")] public BillingSchedule BillingSchedule { get; set; } // FK_BillingScheduleExcludedCptCodes_BillingSchedule

        /// <summary>
        /// Parent CptCode pointed by [BillingScheduleExcludedCptCodes].([CptCodeId]) (FK_BillingScheduleExcludedCptCodes_CptCode)
        /// </summary>
        [InverseProperty("BillingScheduleExcludedCptCodes")]
        [ForeignKey("CptCodeId")] public CptCode CptCode { get; set; } // FK_BillingScheduleExcludedCptCodes_CptCode

        /// <summary>
        /// Parent User pointed by [BillingScheduleExcludedCptCodes].([CreatedById]) (FK_BillingScheduleExcludedCptCodes_CreatedBy)
        /// </summary>
        [InverseProperty("BillingScheduleExcludedCptCodes")]
        [ForeignKey("CreatedById")] public User User { get; set; } // FK_BillingScheduleExcludedCptCodes_CreatedBy

        public BillingScheduleExcludedCptCode()
        {
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
