// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // CaseLoadGoals
    [Table("CaseLoadGoals", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class CaseLoadGoal: IEntity
    {
        // CaseLoadGoal
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_CaseLoadGoals", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"CaseLoadId", Order = 2, TypeName = "int")]
        [Index(@"IX_CaseLoadGoals", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Case load ID")]
        public int CaseLoadId { get; set; } // CaseLoadId

        [Column(@"GoalId", Order = 3, TypeName = "int")]
        [Display(Name = "Goal ID")]
        public int GoalId { get; set; } // GoalId

        [Column(@"Archived", Order = 4, TypeName = "bit")]
        [Display(Name = "Archived")]
        public bool Archived { get; set; } // Archived

        [Column(@"CreatedById", Order = 5, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"ModifiedById", Order = 6, TypeName = "int")]
        [Display(Name = "Modified by ID")]
        public int? ModifiedById { get; set; } // ModifiedById

        [Column(@"DateCreated", Order = 7, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        [Column(@"DateModified", Order = 8, TypeName = "datetime")]
        [Display(Name = "Date modified")]
        public System.DateTime? DateModified { get; set; } // DateModified

        // Foreign keys

        /// <summary>
        /// Parent CaseLoad pointed by [CaseLoadGoals].([CaseLoadId]) (FK_CaseLoadGoals_CaseLoad)
        /// </summary>
        [InverseProperty("CaseLoadGoals")]
        [ForeignKey("CaseLoadId")] public CaseLoad CaseLoad { get; set; } // FK_CaseLoadGoals_CaseLoad

        /// <summary>
        /// Parent User pointed by [CaseLoadGoals].([CreatedById]) (FK_CaseLoadGoals_CreatedBy)
        /// </summary>
        [InverseProperty("CaseLoadGoals_CreatedById")]
        [ForeignKey("CreatedById")] public User CreatedBy { get; set; } // FK_CaseLoadGoals_CreatedBy

        /// <summary>
        /// Parent Goal pointed by [CaseLoadGoals].([GoalId]) (FK_CaseLoadGoals_Goal)
        /// </summary>
        [InverseProperty("CaseLoadGoals")]
        [ForeignKey("GoalId")] public Goal Goal { get; set; } // FK_CaseLoadGoals_Goal

        /// <summary>
        /// Parent User pointed by [CaseLoadGoals].([ModifiedById]) (FK_CaseLoadGoals_ModifiedBy)
        /// </summary>
        [InverseProperty("CaseLoadGoals_ModifiedById")]
        [ForeignKey("ModifiedById")] public User ModifiedBy { get; set; } // FK_CaseLoadGoals_ModifiedBy

        public CaseLoadGoal()
        {
            Archived = false;
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
