// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // CaseLoadCptCodes
    [Table("CaseLoadCptCodes", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class CaseLoadCptCode: IEntity
    {
        // CaseLoadCptCode
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_CaseLoadCptCodes", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"CaseLoadId", Order = 2, TypeName = "int")]
        [Index(@"IX_CaseLoadCptCodes", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Case load ID")]
        public int CaseLoadId { get; set; } // CaseLoadId

        [Column(@"CptCodeId", Order = 3, TypeName = "int")]
        [Display(Name = "Cpt code ID")]
        public int CptCodeId { get; set; } // CptCodeId

        [Column(@"Default", Order = 4, TypeName = "bit")]
        [Display(Name = "Default")]
        public bool? Default { get; set; } // Default

        [Column(@"Archived", Order = 5, TypeName = "bit")]
        [Display(Name = "Archived")]
        public bool Archived { get; set; } // Archived

        [Column(@"CreatedById", Order = 6, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"ModifiedById", Order = 7, TypeName = "int")]
        [Display(Name = "Modified by ID")]
        public int? ModifiedById { get; set; } // ModifiedById

        [Column(@"DateCreated", Order = 8, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        [Column(@"DateModified", Order = 9, TypeName = "datetime")]
        [Display(Name = "Date modified")]
        public System.DateTime? DateModified { get; set; } // DateModified

        // Foreign keys

        /// <summary>
        /// Parent CaseLoad pointed by [CaseLoadCptCodes].([CaseLoadId]) (FK_CaseLoadCptCodes_CaseLoad)
        /// </summary>
        [InverseProperty("CaseLoadCptCodes")]
        [ForeignKey("CaseLoadId")] public CaseLoad CaseLoad { get; set; } // FK_CaseLoadCptCodes_CaseLoad

        /// <summary>
        /// Parent CptCode pointed by [CaseLoadCptCodes].([CptCodeId]) (FK_CaseLoadCptCodes_CptCode)
        /// </summary>
        [InverseProperty("CaseLoadCptCodes")]
        [ForeignKey("CptCodeId")] public CptCode CptCode { get; set; } // FK_CaseLoadCptCodes_CptCode

        /// <summary>
        /// Parent User pointed by [CaseLoadCptCodes].([CreatedById]) (FK_CaseLoadCptCodes_CreatedBy)
        /// </summary>
        [InverseProperty("CaseLoadCptCodes_CreatedById")]
        [ForeignKey("CreatedById")] public User CreatedBy { get; set; } // FK_CaseLoadCptCodes_CreatedBy

        /// <summary>
        /// Parent User pointed by [CaseLoadCptCodes].([ModifiedById]) (FK_CaseLoadCptCodes_ModifiedBy)
        /// </summary>
        [InverseProperty("CaseLoadCptCodes_ModifiedById")]
        [ForeignKey("ModifiedById")] public User ModifiedBy { get; set; } // FK_CaseLoadCptCodes_ModifiedBy

        public CaseLoadCptCode()
        {
            Default = false;
            Archived = false;
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
