// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // CaseLoadMethods
    [Table("CaseLoadMethods", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class CaseLoadMethod: IEntity
    {
        // CaseLoadMethod
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_CaseLoadMethods", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"CaseLoadId", Order = 2, TypeName = "int")]
        [Display(Name = "Case load ID")]
        public int CaseLoadId { get; set; } // CaseLoadId

        [Column(@"MethodId", Order = 3, TypeName = "int")]
        [Display(Name = "Method ID")]
        public int MethodId { get; set; } // MethodId

        [Column(@"Archived", Order = 4, TypeName = "bit")]
        [Display(Name = "Archived")]
        public bool Archived { get; set; } // Archived

        [Column(@"CreatedById", Order = 5, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"ModifiedById", Order = 6, TypeName = "int")]
        [Display(Name = "Modified by ID")]
        public int? ModifiedById { get; set; } // ModifiedById

        [Column(@"DateCreated", Order = 7, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        [Column(@"DateModified", Order = 8, TypeName = "datetime")]
        [Display(Name = "Date modified")]
        public System.DateTime? DateModified { get; set; } // DateModified

        // Foreign keys

        /// <summary>
        /// Parent CaseLoad pointed by [CaseLoadMethods].([CaseLoadId]) (FK_CaseLoadMethods_CaseLoad)
        /// </summary>
        [InverseProperty("CaseLoadMethods")]
        [ForeignKey("CaseLoadId")] public CaseLoad CaseLoad { get; set; } // FK_CaseLoadMethods_CaseLoad

        /// <summary>
        /// Parent User pointed by [CaseLoadMethods].([CreatedById]) (FK_CaseLoadMethods_CreatedBy)
        /// </summary>
        [InverseProperty("CaseLoadMethods_CreatedById")]
        [ForeignKey("CreatedById")] public User CreatedBy { get; set; } // FK_CaseLoadMethods_CreatedBy

        /// <summary>
        /// Parent Method pointed by [CaseLoadMethods].([MethodId]) (FK_CaseLoadMethods_Method)
        /// </summary>
        [InverseProperty("CaseLoadMethods")]
        [ForeignKey("MethodId")] public Method Method { get; set; } // FK_CaseLoadMethods_Method

        /// <summary>
        /// Parent User pointed by [CaseLoadMethods].([ModifiedById]) (FK_CaseLoadMethods_ModifiedBy)
        /// </summary>
        [InverseProperty("CaseLoadMethods_ModifiedById")]
        [ForeignKey("ModifiedById")] public User ModifiedBy { get; set; } // FK_CaseLoadMethods_ModifiedBy

        public CaseLoadMethod()
        {
            Archived = false;
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
