// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // ClaimsEncounters
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class ClaimsEncounterConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ClaimsEncounter>
    {
        public ClaimsEncounterConfiguration()
            : this("dbo")
        {
        }

        public ClaimsEncounterConfiguration(string schema)
        {
            Property(x => x.ClaimAmount).IsUnicode(false);
            Property(x => x.ProcedureIdentifier).IsUnicode(false);
            Property(x => x.BillingUnits).IsUnicode(false);
            Property(x => x.PhysicianFirstName).IsOptional().IsUnicode(false);
            Property(x => x.PhysicianLastName).IsOptional().IsUnicode(false);
            Property(x => x.PhysicianId).IsOptional().IsUnicode(false);
            Property(x => x.ReferringProviderFirstName).IsOptional().IsUnicode(false);
            Property(x => x.ReferringProviderLastName).IsOptional().IsUnicode(false);
            Property(x => x.ReasonForServiceCode).IsUnicode(false);
            Property(x => x.ReferringProviderId).IsUnicode(false);
            Property(x => x.EdiErrorCodeId).IsOptional();
            Property(x => x.ClaimId).IsOptional().IsUnicode(false);
            Property(x => x.ClaimsStudentId).IsOptional();
            Property(x => x.AggregateId).IsOptional();
            Property(x => x.PaidAmount).IsOptional().IsUnicode(false);
            Property(x => x.VoucherDate).IsOptional();
            Property(x => x.ReferenceNumber).IsOptional().IsUnicode(false);
            Property(x => x.AdjustmentReasonCode).IsOptional().IsUnicode(false);
            Property(x => x.AdjustmentAmount).IsOptional().IsUnicode(false);
            Property(x => x.ControlNumberPrefix).IsOptional().IsUnicode(false);
            Property(x => x.ReversedClaimId).IsOptional();

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
