// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // EdiMetaDatas
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class EdiMetaDataConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<EdiMetaData>
    {
        public EdiMetaDataConfiguration()
            : this("dbo")
        {
        }

        public EdiMetaDataConfiguration(string schema)
        {
            Property(x => x.ReceiverId).IsUnicode(false);
            Property(x => x.ClaimImplementationReference).IsUnicode(false);
            Property(x => x.RosterValidationImplementationReference).IsUnicode(false);
            Property(x => x.SubmitterOrganizationName).IsUnicode(false);
            Property(x => x.SubmitterQlfrId).IsUnicode(false);
            Property(x => x.SubmitterName).IsUnicode(false);
            Property(x => x.SubmitterPhone).IsUnicode(false);
            Property(x => x.SubmitterPhoneAlt).IsUnicode(false);
            Property(x => x.SubmitterEmail).IsUnicode(false);
            Property(x => x.ReceiverOrganizationName).IsUnicode(false);
            Property(x => x.ProviderCode).IsUnicode(false);
            Property(x => x.ReferenceQlfrId).IsUnicode(false);
            Property(x => x.ProviderOrganizationName).IsUnicode(false);
            Property(x => x.ServiceLocationCode).IsUnicode(false);
            Property(x => x.ClaimNoteDescription).IsUnicode(false);
            Property(x => x.FacilityCode).IsUnicode(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
