// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // EdiMetaDatas
    [Table("EdiMetaDatas", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class EdiMetaData: IEntity
    {
        // EdiMetaData
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_EdiMetaDatas", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"SenderId", Order = 2, TypeName = "int")]
        [Display(Name = "Sender ID")]
        public int SenderId { get; set; } // SenderId

        [Column(@"ReceiverId", Order = 3, TypeName = "varchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Receiver ID")]
        public string ReceiverId { get; set; } // ReceiverId (length: 20)

        [Column(@"ClaimImplementationReference", Order = 4, TypeName = "varchar")]
        [MaxLength(35)]
        [StringLength(35)]
        [Display(Name = "Claim implementation reference")]
        public string ClaimImplementationReference { get; set; } // ClaimImplementationReference (length: 35)

        [Column(@"RosterValidationImplementationReference", Order = 5, TypeName = "varchar")]
        [MaxLength(35)]
        [StringLength(35)]
        [Display(Name = "Roster validation implementation reference")]
        public string RosterValidationImplementationReference { get; set; } // RosterValidationImplementationReference (length: 35)

        [Column(@"SubmitterOrganizationName", Order = 6, TypeName = "varchar")]
        [MaxLength(60)]
        [StringLength(60)]
        [Display(Name = "Submitter organization name")]
        public string SubmitterOrganizationName { get; set; } // SubmitterOrganizationName (length: 60)

        [Column(@"SubmitterQlfrId", Order = 7, TypeName = "varchar")]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Submitter qlfr ID")]
        public string SubmitterQlfrId { get; set; } // SubmitterQlfrId (length: 2)

        [Column(@"SubmitterName", Order = 8, TypeName = "varchar")]
        [MaxLength(60)]
        [StringLength(60)]
        [Display(Name = "Submitter name")]
        public string SubmitterName { get; set; } // SubmitterName (length: 60)

        [Column(@"SubmitterPhone", Order = 9, TypeName = "varchar")]
        [MaxLength(256)]
        [StringLength(256)]
        [Display(Name = "Submitter phone")]
        public string SubmitterPhone { get; set; } // SubmitterPhone (length: 256)

        [Column(@"SubmitterPhoneAlt", Order = 10, TypeName = "varchar")]
        [MaxLength(256)]
        [StringLength(256)]
        [Display(Name = "Submitter phone alt")]
        public string SubmitterPhoneAlt { get; set; } // SubmitterPhoneAlt (length: 256)

        [Column(@"SubmitterEmail", Order = 11, TypeName = "varchar")]
        [MaxLength(256)]
        [StringLength(256)]
        [Display(Name = "Submitter email")]
        public string SubmitterEmail { get; set; } // SubmitterEmail (length: 256)

        [Column(@"ReceiverOrganizationName", Order = 12, TypeName = "varchar")]
        [MaxLength(60)]
        [StringLength(60)]
        [Display(Name = "Receiver organization name")]
        public string ReceiverOrganizationName { get; set; } // ReceiverOrganizationName (length: 60)

        [Column(@"ProviderCode", Order = 13, TypeName = "varchar")]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Provider code")]
        public string ProviderCode { get; set; } // ProviderCode (length: 2)

        [Column(@"ReferenceQlfrId", Order = 14, TypeName = "varchar")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Reference qlfr ID")]
        public string ReferenceQlfrId { get; set; } // ReferenceQlfrId (length: 3)

        [Column(@"ProviderOrganizationName", Order = 15, TypeName = "varchar")]
        [MaxLength(60)]
        [StringLength(60)]
        [Display(Name = "Provider organization name")]
        public string ProviderOrganizationName { get; set; } // ProviderOrganizationName (length: 60)

        [Column(@"ServiceLocationCode", Order = 16, TypeName = "varchar")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Service location code")]
        public string ServiceLocationCode { get; set; } // ServiceLocationCode (length: 10)

        [Column(@"ClaimNoteDescription", Order = 17, TypeName = "varchar")]
        [MaxLength(80)]
        [StringLength(80)]
        [Display(Name = "Claim note description")]
        public string ClaimNoteDescription { get; set; } // ClaimNoteDescription (length: 80)

        [Column(@"FacilityCode", Order = 18, TypeName = "varchar")]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Facility code")]
        public string FacilityCode { get; set; } // FacilityCode (length: 2)

        public EdiMetaData()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
