// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // EncounterStudentStatuses
    [Table("EncounterStudentStatuses", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class EncounterStudentStatus: IEntity
    {
        // EncounterStudentStatus
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_EncounterStudentStatuses", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"EncounterStudentId", Order = 2, TypeName = "int")]
        [Display(Name = "Encounter student ID")]
        public int EncounterStudentId { get; set; } // EncounterStudentId

        [Column(@"EncounterStatusId", Order = 3, TypeName = "int")]
        [Display(Name = "Encounter status ID")]
        public int EncounterStatusId { get; set; } // EncounterStatusId

        [Column(@"CreatedById", Order = 4, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"DateCreated", Order = 5, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [EncounterStudentStatuses].([CreatedById]) (FK_EncounterStudentStatuses_CreatedBy)
        /// </summary>
        [InverseProperty("EncounterStudentStatus")]
        [ForeignKey("CreatedById")] public User CreatedBy { get; set; } // FK_EncounterStudentStatuses_CreatedBy

        /// <summary>
        /// Parent EncounterStatus pointed by [EncounterStudentStatuses].([EncounterStatusId]) (FK_EncounterStudentStatuses_EncounterStatus)
        /// </summary>
        [InverseProperty("EncounterStudentStatus")]
        [ForeignKey("EncounterStatusId")] public EncounterStatus EncounterStatus { get; set; } // FK_EncounterStudentStatuses_EncounterStatus

        /// <summary>
        /// Parent EncounterStudent pointed by [EncounterStudentStatuses].([EncounterStudentId]) (FK_EncounterStudentStatuses_EncounterStudent)
        /// </summary>
        [InverseProperty("EncounterStudentStatus")]
        [ForeignKey("EncounterStudentId")] public EncounterStudent EncounterStudent { get; set; } // FK_EncounterStudentStatuses_EncounterStudent

        public EncounterStudentStatus()
        {
            EncounterStatusId = 1;
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
