// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // EncounterStudentGoals
    [Table("EncounterStudentGoals", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class EncounterStudentGoal: IEntity
    {
        // EncounterStudentGoal
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_EncounterStudentGoals", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"EncounterStudentId", Order = 2, TypeName = "int")]
        [Display(Name = "Encounter student ID")]
        public int EncounterStudentId { get; set; } // EncounterStudentId

        [Column(@"GoalId", Order = 3, TypeName = "int")]
        [Display(Name = "Goal ID")]
        public int GoalId { get; set; } // GoalId

        [Column(@"ServiceOutcomes", Order = 4, TypeName = "varchar")]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Service outcomes")]
        public string ServiceOutcomes { get; set; } // ServiceOutcomes (length: 250)

        [Column(@"Archived", Order = 5, TypeName = "bit")]
        [Display(Name = "Archived")]
        public bool Archived { get; set; } // Archived

        [Column(@"CreatedById", Order = 6, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"ModifiedById", Order = 7, TypeName = "int")]
        [Display(Name = "Modified by ID")]
        public int? ModifiedById { get; set; } // ModifiedById

        [Column(@"DateCreated", Order = 8, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        [Column(@"DateModified", Order = 9, TypeName = "datetime")]
        [Display(Name = "Date modified")]
        public System.DateTime? DateModified { get; set; } // DateModified

        [Column(@"NursingResponseNote", Order = 10, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Nursing response note")]
        public string NursingResponseNote { get; set; } // NursingResponseNote (length: 50)

        [Column(@"NursingResultNote", Order = 11, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Nursing result note")]
        public string NursingResultNote { get; set; } // NursingResultNote (length: 50)

        [Column(@"NursingGoalResultId", Order = 12, TypeName = "int")]
        [Display(Name = "Nursing goal result ID")]
        public int? NursingGoalResultId { get; set; } // NursingGoalResultId

        [Column(@"CaseLoadScriptGoalId", Order = 13, TypeName = "int")]
        [Display(Name = "Case load script goal ID")]
        public int? CaseLoadScriptGoalId { get; set; } // CaseLoadScriptGoalId

        // Foreign keys

        /// <summary>
        /// Parent CaseLoadScriptGoal pointed by [EncounterStudentGoals].([CaseLoadScriptGoalId]) (FK_EncounterStudentGoals_CaseLoadScriptGoals)
        /// </summary>
        [InverseProperty("EncounterStudentGoals")]
        [ForeignKey("CaseLoadScriptGoalId")] public CaseLoadScriptGoal CaseLoadScriptGoal { get; set; } // FK_EncounterStudentGoals_CaseLoadScriptGoals

        /// <summary>
        /// Parent User pointed by [EncounterStudentGoals].([CreatedById]) (FK_EncounterStudentGoals_CreatedBy)
        /// </summary>
        [InverseProperty("EncounterStudentGoals_CreatedById")]
        [ForeignKey("CreatedById")] public User CreatedBy { get; set; } // FK_EncounterStudentGoals_CreatedBy

        /// <summary>
        /// Parent EncounterStudent pointed by [EncounterStudentGoals].([EncounterStudentId]) (FK_EncounterStudentGoals_EncounterStudent)
        /// </summary>
        [InverseProperty("EncounterStudentGoals")]
        [ForeignKey("EncounterStudentId")] public EncounterStudent EncounterStudent { get; set; } // FK_EncounterStudentGoals_EncounterStudent

        /// <summary>
        /// Parent Goal pointed by [EncounterStudentGoals].([GoalId]) (FK_EncounterStudentGoals_Goal)
        /// </summary>
        [InverseProperty("EncounterStudentGoals")]
        [ForeignKey("GoalId")] public Goal Goal { get; set; } // FK_EncounterStudentGoals_Goal

        /// <summary>
        /// Parent User pointed by [EncounterStudentGoals].([ModifiedById]) (FK_EncounterStudentGoals_ModifiedBy)
        /// </summary>
        [InverseProperty("EncounterStudentGoals_ModifiedById")]
        [ForeignKey("ModifiedById")] public User ModifiedBy { get; set; } // FK_EncounterStudentGoals_ModifiedBy

        /// <summary>
        /// Parent NursingGoalResult pointed by [EncounterStudentGoals].([NursingGoalResultId]) (FK_EncounterStudentGoals_NursingGoalResult)
        /// </summary>
        [InverseProperty("EncounterStudentGoals")]
        [ForeignKey("NursingGoalResultId")] public NursingGoalResult NursingGoalResult { get; set; } // FK_EncounterStudentGoals_NursingGoalResult

        public EncounterStudentGoal()
        {
            Archived = false;
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
