// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // EvaluationTypesDiagnosisCodes
    [Table("EvaluationTypesDiagnosisCodes", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class EvaluationTypesDiagnosisCode: IEntity
    {
        // EvaluationTypesDiagnosisCode
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_EvaluationTypesDiagnosisCodes", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"EvaluationTypeId", Order = 2, TypeName = "int")]
        [Display(Name = "Evaluation type ID")]
        public int EvaluationTypeId { get; set; } // EvaluationTypeId

        [Column(@"DiagnosisCodeId", Order = 3, TypeName = "int")]
        [Display(Name = "Diagnosis code ID")]
        public int DiagnosisCodeId { get; set; } // DiagnosisCodeId

        [Column(@"Archived", Order = 4, TypeName = "bit")]
        [Display(Name = "Archived")]
        public bool Archived { get; set; } // Archived

        [Column(@"CreatedById", Order = 5, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"ModifiedById", Order = 6, TypeName = "int")]
        [Display(Name = "Modified by ID")]
        public int? ModifiedById { get; set; } // ModifiedById

        [Column(@"DateCreated", Order = 7, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        [Column(@"DateModified", Order = 8, TypeName = "datetime")]
        [Display(Name = "Date modified")]
        public System.DateTime? DateModified { get; set; } // DateModified

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [EvaluationTypesDiagnosisCodes].([CreatedById]) (FK_EvaluationTypesDiagnosisCodes_CreatedBy)
        /// </summary>
        [InverseProperty("EvaluationTypesDiagnosisCodes_CreatedById")]
        [ForeignKey("CreatedById")] public User CreatedBy { get; set; } // FK_EvaluationTypesDiagnosisCodes_CreatedBy

        /// <summary>
        /// Parent DiagnosisCode pointed by [EvaluationTypesDiagnosisCodes].([DiagnosisCodeId]) (FK_EvaluationTypesDiagnosisCodes_DiagnosisCodes)
        /// </summary>
        [InverseProperty("EvaluationTypesDiagnosisCodes")]
        [ForeignKey("DiagnosisCodeId")] public DiagnosisCode DiagnosisCode { get; set; } // FK_EvaluationTypesDiagnosisCodes_DiagnosisCodes

        /// <summary>
        /// Parent EvaluationType pointed by [EvaluationTypesDiagnosisCodes].([EvaluationTypeId]) (FK_EvaluationTypesDiagnosisCodes_EvaluationTypes)
        /// </summary>
        [InverseProperty("EvaluationTypesDiagnosisCodes")]
        [ForeignKey("EvaluationTypeId")] public EvaluationType EvaluationType { get; set; } // FK_EvaluationTypesDiagnosisCodes_EvaluationTypes

        /// <summary>
        /// Parent User pointed by [EvaluationTypesDiagnosisCodes].([ModifiedById]) (FK_EvaluationTypesDiagnosisCodes_ModifiedBy)
        /// </summary>
        [InverseProperty("EvaluationTypesDiagnosisCodes_ModifiedById")]
        [ForeignKey("ModifiedById")] public User ModifiedBy { get; set; } // FK_EvaluationTypesDiagnosisCodes_ModifiedBy

        public EvaluationTypesDiagnosisCode()
        {
            Archived = false;
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
