// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // MergedStudents
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class MergedStudentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MergedStudent>
    {
        public MergedStudentConfiguration()
            : this("dbo")
        {
        }

        public MergedStudentConfiguration(string schema)
        {
            Property(x => x.FirstName).IsUnicode(false);
            Property(x => x.MiddleName).IsOptional().IsUnicode(false);
            Property(x => x.LastName).IsUnicode(false);
            Property(x => x.StudentCode).IsUnicode(false);
            Property(x => x.Grade).IsUnicode(false);
            Property(x => x.AddressId).IsOptional();
            Property(x => x.DateCreated).IsOptional();

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
