// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // MessageDocuments
    [Table("MessageDocuments", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class MessageDocument: IEntity
    {
        // MessageDocument

        ///<summary>
        /// Module
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_MessageDocuments", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"Description", Order = 2, TypeName = "varchar")]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Description")]
        public string Description { get; set; } // Description (length: 200)

        [Column(@"FilePath", Order = 3, TypeName = "varchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "File path")]
        public string FilePath { get; set; } // FilePath (length: 500)

        [Column(@"FileName", Order = 4, TypeName = "varchar")]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "File name")]
        public string FileName { get; set; } // FileName (length: 200)

        [Column(@"ValidTill", Order = 5, TypeName = "datetime")]
        [Display(Name = "Valid till")]
        public System.DateTime? ValidTill { get; set; } // ValidTill

        [Column(@"Mandatory", Order = 6, TypeName = "bit")]
        [Display(Name = "Mandatory")]
        public bool Mandatory { get; set; } // Mandatory

        [Column(@"TrainingTypeId", Order = 7, TypeName = "int")]
        [Display(Name = "Training type ID")]
        public int? TrainingTypeId { get; set; } // TrainingTypeId

        [Column(@"DueDate", Order = 8, TypeName = "datetime")]
        [Display(Name = "Due date")]
        public System.DateTime? DueDate { get; set; } // DueDate

        [Column(@"CreatedById", Order = 9, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"ModifiedById", Order = 10, TypeName = "int")]
        [Display(Name = "Modified by ID")]
        public int? ModifiedById { get; set; } // ModifiedById

        [Column(@"DateCreated", Order = 11, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime DateCreated { get; set; } // DateCreated

        [Column(@"DateModified", Order = 12, TypeName = "datetime")]
        [Display(Name = "Date modified")]
        public System.DateTime? DateModified { get; set; } // DateModified

        [Column(@"Archived", Order = 13, TypeName = "bit")]
        [Display(Name = "Archived")]
        public bool Archived { get; set; } // Archived

        [Column(@"MessageFilterTypeId", Order = 14, TypeName = "int")]
        [Display(Name = "Message filter type ID")]
        public int MessageFilterTypeId { get; set; } // MessageFilterTypeId

        [Column(@"ServiceCodeId", Order = 15, TypeName = "int")]
        [Display(Name = "Service code ID")]
        public int? ServiceCodeId { get; set; } // ServiceCodeId

        [Column(@"SchoolDistrictId", Order = 16, TypeName = "int")]
        [Display(Name = "School district ID")]
        public int? SchoolDistrictId { get; set; } // SchoolDistrictId

        [Column(@"ForDistrictAdmins", Order = 17, TypeName = "bit")]
        [Display(Name = "For district admins")]
        public bool ForDistrictAdmins { get; set; } // ForDistrictAdmins

        [Column(@"ProviderTitleId", Order = 18, TypeName = "int")]
        [Display(Name = "Provider title ID")]
        public int? ProviderTitleId { get; set; } // ProviderTitleId

        [Column(@"ProviderId", Order = 19, TypeName = "int")]
        [Display(Name = "Provider ID")]
        public int? ProviderId { get; set; } // ProviderId

        [Column(@"EscId", Order = 20, TypeName = "int")]
        [Display(Name = "Esc ID")]
        public int? EscId { get; set; } // EscId

        // Reverse navigation

        /// <summary>
        /// Child ProviderTrainings where [ProviderTrainings].[DocumentId] point to this entity (FK_ProviderTrainings_MessageDocument)
        /// </summary>
        public System.Collections.Generic.ICollection<ProviderTraining> ProviderTrainings { get; set; } // ProviderTrainings.FK_ProviderTrainings_MessageDocument

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [MessageDocuments].([CreatedById]) (FK_MessageDocuments_CreatedBy)
        /// </summary>
        [InverseProperty("MessageDocuments_CreatedById")]
        [ForeignKey("CreatedById")] public User CreatedBy { get; set; } // FK_MessageDocuments_CreatedBy

        /// <summary>
        /// Parent Esc pointed by [MessageDocuments].([EscId]) (FK_MessageDocument_Escs)
        /// </summary>
        [InverseProperty("MessageDocuments")]
        [ForeignKey("EscId")] public Esc Esc { get; set; } // FK_MessageDocument_Escs

        /// <summary>
        /// Parent MessageFilterType pointed by [MessageDocuments].([MessageFilterTypeId]) (FK_MessageDocuments_MessageFilterTypes)
        /// </summary>
        [InverseProperty("MessageDocuments")]
        [ForeignKey("MessageFilterTypeId")] public MessageFilterType MessageFilterType { get; set; } // FK_MessageDocuments_MessageFilterTypes

        /// <summary>
        /// Parent User pointed by [MessageDocuments].([ModifiedById]) (FK_MessageDocuments_ModifiedBy)
        /// </summary>
        [InverseProperty("MessageDocuments_ModifiedById")]
        [ForeignKey("ModifiedById")] public User ModifiedBy { get; set; } // FK_MessageDocuments_ModifiedBy

        /// <summary>
        /// Parent Provider pointed by [MessageDocuments].([ProviderId]) (FK_MessageDocument_Providers)
        /// </summary>
        [InverseProperty("MessageDocuments")]
        [ForeignKey("ProviderId")] public Provider Provider { get; set; } // FK_MessageDocument_Providers

        /// <summary>
        /// Parent ProviderTitle pointed by [MessageDocuments].([ProviderTitleId]) (FK_MessageDocument_ProviderTitles)
        /// </summary>
        [InverseProperty("MessageDocuments")]
        [ForeignKey("ProviderTitleId")] public ProviderTitle ProviderTitle { get; set; } // FK_MessageDocument_ProviderTitles

        /// <summary>
        /// Parent SchoolDistrict pointed by [MessageDocuments].([SchoolDistrictId]) (FK_MessageDocument_SchoolDistricts)
        /// </summary>
        [InverseProperty("MessageDocuments")]
        [ForeignKey("SchoolDistrictId")] public SchoolDistrict SchoolDistrict { get; set; } // FK_MessageDocument_SchoolDistricts

        /// <summary>
        /// Parent ServiceCode pointed by [MessageDocuments].([ServiceCodeId]) (FK_MessageDocument_ServiceCodes)
        /// </summary>
        [InverseProperty("MessageDocuments")]
        [ForeignKey("ServiceCodeId")] public ServiceCode ServiceCode { get; set; } // FK_MessageDocument_ServiceCodes

        /// <summary>
        /// Parent TrainingType pointed by [MessageDocuments].([TrainingTypeId]) (FK_MessageDocuments_TrainingType)
        /// </summary>
        [InverseProperty("MessageDocuments")]
        [ForeignKey("TrainingTypeId")] public TrainingType TrainingType { get; set; } // FK_MessageDocuments_TrainingType

        public MessageDocument()
        {
            Mandatory = false;
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            Archived = false;
            ForDistrictAdmins = false;
            ProviderTrainings = new System.Collections.Generic.List<ProviderTraining>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
