// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // MessageDocuments
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class MessageDocumentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MessageDocument>
    {
        public MessageDocumentConfiguration()
            : this("dbo")
        {
        }

        public MessageDocumentConfiguration(string schema)
        {
            Property(x => x.Description).IsUnicode(false);
            Property(x => x.FilePath).IsUnicode(false);
            Property(x => x.FileName).IsUnicode(false);
            Property(x => x.ValidTill).IsOptional();
            Property(x => x.TrainingTypeId).IsOptional();
            Property(x => x.DueDate).IsOptional();
            Property(x => x.ModifiedById).IsOptional();
            Property(x => x.DateModified).IsOptional();
            Property(x => x.ServiceCodeId).IsOptional();
            Property(x => x.SchoolDistrictId).IsOptional();
            Property(x => x.ProviderTitleId).IsOptional();
            Property(x => x.ProviderId).IsOptional();
            Property(x => x.EscId).IsOptional();

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
