// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // Migration_ProviderCaseNotesHistory
    [Table("Migration_ProviderCaseNotesHistory", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class MigrationProviderCaseNotesHistory: IEntity
    {
        // Migration_ProviderCaseNotesHistory
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_Migration_ProviderCaseNotesHistory", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"ProviderId", Order = 2, TypeName = "int")]
        [Index(@"IX_Migration_ProviderCaseNotesHistory_ProviderId", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Provider ID")]
        public int ProviderId { get; set; } // ProviderId

        [Column(@"StudentId", Order = 3, TypeName = "int")]
        [Display(Name = "Student ID")]
        public int StudentId { get; set; } // StudentId

        [Column(@"EncounterNumber", Order = 4, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Encounter number")]
        public string EncounterNumber { get; set; } // EncounterNumber (length: 50)

        [Column(@"EncounterDate", Order = 5, TypeName = "datetime")]
        [Display(Name = "Encounter date")]
        public System.DateTime EncounterDate { get; set; } // EncounterDate

        [Column(@"StartTime", Order = 6, TypeName = "datetime")]
        [Display(Name = "Start time")]
        public System.DateTime StartTime { get; set; } // StartTime

        [Column(@"EndTime", Order = 7, TypeName = "datetime")]
        [Display(Name = "End time")]
        public System.DateTime EndTime { get; set; } // EndTime

        [Column(@"ProviderNotes", Order = 8, TypeName = "varchar(max)")]
        [Display(Name = "Provider notes")]
        public string ProviderNotes { get; set; } // ProviderNotes

        // Foreign keys

        /// <summary>
        /// Parent Provider pointed by [Migration_ProviderCaseNotesHistory].([ProviderId]) (FK_Migration_ProviderCaseNotesHistory_Provider)
        /// </summary>
        [InverseProperty("MigrationProviderCaseNotesHistories")]
        [ForeignKey("ProviderId")] public Provider Provider { get; set; } // FK_Migration_ProviderCaseNotesHistory_Provider

        /// <summary>
        /// Parent Student pointed by [Migration_ProviderCaseNotesHistory].([StudentId]) (FK_Migration_ProviderCaseNotesHistory_Student)
        /// </summary>
        [InverseProperty("MigrationProviderCaseNotesHistories")]
        [ForeignKey("StudentId")] public Student Student { get; set; } // FK_Migration_ProviderCaseNotesHistory_Student

        public MigrationProviderCaseNotesHistory()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
