// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // NursingGoalResults
    [Table("NursingGoalResults", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class NursingGoalResult: IEntity, IBasicNameEntity
    {
        // NursingGoalResult
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_NursingGoalResults", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"Name", Order = 2, TypeName = "varchar")]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 250)

        [Column(@"ResultsNote", Order = 3, TypeName = "bit")]
        [Display(Name = "Results note")]
        public bool ResultsNote { get; set; } // ResultsNote

        [Column(@"Archived", Order = 4, TypeName = "bit")]
        [Display(Name = "Archived")]
        public bool Archived { get; set; } // Archived

        // Reverse navigation

        /// <summary>
        /// Child EncounterStudentGoals where [EncounterStudentGoals].[NursingGoalResultId] point to this entity (FK_EncounterStudentGoals_NursingGoalResult)
        /// </summary>
        public System.Collections.Generic.ICollection<EncounterStudentGoal> EncounterStudentGoals { get; set; } // EncounterStudentGoals.FK_EncounterStudentGoals_NursingGoalResult
        /// <summary>
        /// Child NursingGoalResponses (Many-to-Many) mapped by table [NursingGoalResponseResults]
        /// </summary>
        public System.Collections.Generic.ICollection<NursingGoalResponse> NursingGoalResponses { get; set; } // Many to many mapping

        public NursingGoalResult()
        {
            ResultsNote = false;
            Archived = false;
            EncounterStudentGoals = new System.Collections.Generic.List<EncounterStudentGoal>();
            NursingGoalResponses = new System.Collections.Generic.List<NursingGoalResponse>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
