// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // ProviderLicenses
    [Table("ProviderLicenses", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class ProviderLicens: IEntity
    {
        // ProviderLicens
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_ProviderLicenses", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"ProviderId", Order = 2, TypeName = "int")]
        [Display(Name = "Provider ID")]
        public int ProviderId { get; set; } // ProviderId

        [Column(@"License", Order = 3, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "License")]
        public string License { get; set; } // License (length: 50)

        [Column(@"AsOfDate", Order = 4, TypeName = "datetime")]
        [Display(Name = "As of date")]
        public System.DateTime AsOfDate { get; set; } // AsOfDate

        [Column(@"ExpirationDate", Order = 5, TypeName = "datetime")]
        [Display(Name = "Expiration date")]
        public System.DateTime ExpirationDate { get; set; } // ExpirationDate

        [Column(@"CreatedById", Order = 6, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"DateCreated", Order = 7, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [ProviderLicenses].([CreatedById]) (FK_ProviderLicenses_CreatedBy)
        /// </summary>
        [InverseProperty("ProviderLicens")]
        [ForeignKey("CreatedById")] public User User { get; set; } // FK_ProviderLicenses_CreatedBy

        /// <summary>
        /// Parent Provider pointed by [ProviderLicenses].([ProviderId]) (FK_ProviderLicenses_Providers)
        /// </summary>
        [InverseProperty("ProviderLicens")]
        [ForeignKey("ProviderId")] public Provider Provider { get; set; } // FK_ProviderLicenses_Providers

        public ProviderLicens()
        {
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
