// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // ProviderAcknowledgmentLogs
    [Table("ProviderAcknowledgmentLogs", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class ProviderAcknowledgmentLog: IEntity
    {
        // ProviderAcknowledgmentLog
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_ProviderAcknowledgmentLogs", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"ProviderId", Order = 2, TypeName = "int")]
        [Display(Name = "Provider ID")]
        public int ProviderId { get; set; } // ProviderId

        [Column(@"DateAcknowledged", Order = 3, TypeName = "datetime")]
        [Display(Name = "Date acknowledged")]
        public System.DateTime DateAcknowledged { get; set; } // DateAcknowledged

        // Foreign keys

        /// <summary>
        /// Parent Provider pointed by [ProviderAcknowledgmentLogs].([ProviderId]) (FK_ProviderAcknowledgmentLogs_Providers)
        /// </summary>
        [InverseProperty("ProviderAcknowledgmentLogs")]
        [ForeignKey("ProviderId")] public Provider Provider { get; set; } // FK_ProviderAcknowledgmentLogs_Providers

        public ProviderAcknowledgmentLog()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
