// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // ProviderStudentSupervisors
    [Table("ProviderStudentSupervisors", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class ProviderStudentSupervisor: IEntity
    {
        // ProviderStudentSupervisor

        ///<summary>
        /// Module
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_ProviderStudentSupervisors", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"AssistantId", Order = 2, TypeName = "int")]
        [Index(@"IX_ProviderStudentSupervisors_AssistantId", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Assistant ID")]
        public int AssistantId { get; set; } // AssistantId

        [Column(@"SupervisorId", Order = 3, TypeName = "int")]
        [Index(@"IX_ProviderStudentSupervisors_StudentId_SupervisorId_EffectiveEndDate", 2, IsUnique = false, IsClustered = false)]
        [Display(Name = "Supervisor ID")]
        public int SupervisorId { get; set; } // SupervisorId

        [Column(@"StudentId", Order = 4, TypeName = "int")]
        [Index(@"IX_ProviderStudentSupervisors_StudentId_SupervisorId_EffectiveEndDate", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Student ID")]
        public int StudentId { get; set; } // StudentId

        [Column(@"EffectiveStartDate", Order = 5, TypeName = "datetime")]
        [Display(Name = "Effective start date")]
        public System.DateTime EffectiveStartDate { get; set; } // EffectiveStartDate

        [Column(@"EffectiveEndDate", Order = 6, TypeName = "datetime")]
        [Index(@"IX_ProviderStudentSupervisors_StudentId_SupervisorId_EffectiveEndDate", 3, IsUnique = false, IsClustered = false)]
        [Display(Name = "Effective end date")]
        public System.DateTime? EffectiveEndDate { get; set; } // EffectiveEndDate

        [Column(@"CreatedById", Order = 7, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"ModifiedById", Order = 8, TypeName = "int")]
        [Display(Name = "Modified by ID")]
        public int? ModifiedById { get; set; } // ModifiedById

        [Column(@"DateCreated", Order = 9, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        [Column(@"DateModified", Order = 10, TypeName = "datetime")]
        [Display(Name = "Date modified")]
        public System.DateTime? DateModified { get; set; } // DateModified

        // Foreign keys

        /// <summary>
        /// Parent Provider pointed by [ProviderStudentSupervisors].([AssistantId]) (FK_ProviderStudentSupervisors_Assistant)
        /// </summary>
        [InverseProperty("ProviderStudentSupervisors_AssistantId")]
        [ForeignKey("AssistantId")] public Provider Assistant { get; set; } // FK_ProviderStudentSupervisors_Assistant

        /// <summary>
        /// Parent User pointed by [ProviderStudentSupervisors].([CreatedById]) (FK_ProviderStudentSupervisors_CreatedBy)
        /// </summary>
        [InverseProperty("ProviderStudentSupervisors_CreatedById")]
        [ForeignKey("CreatedById")] public User CreatedBy { get; set; } // FK_ProviderStudentSupervisors_CreatedBy

        /// <summary>
        /// Parent User pointed by [ProviderStudentSupervisors].([ModifiedById]) (FK_ProviderStudentSupervisors_ModifiedBy)
        /// </summary>
        [InverseProperty("ProviderStudentSupervisors_ModifiedById")]
        [ForeignKey("ModifiedById")] public User ModifiedBy { get; set; } // FK_ProviderStudentSupervisors_ModifiedBy

        /// <summary>
        /// Parent Student pointed by [ProviderStudentSupervisors].([StudentId]) (FK_ProviderStudentSupervisors_Students)
        /// </summary>
        [InverseProperty("ProviderStudentSupervisors")]
        [ForeignKey("StudentId")] public Student Student { get; set; } // FK_ProviderStudentSupervisors_Students

        /// <summary>
        /// Parent Provider pointed by [ProviderStudentSupervisors].([SupervisorId]) (FK_ProviderStudentSupervisors_Supervisor)
        /// </summary>
        [InverseProperty("ProviderStudentSupervisors_SupervisorId")]
        [ForeignKey("SupervisorId")] public Provider Supervisor { get; set; } // FK_ProviderStudentSupervisors_Supervisor

        public ProviderStudentSupervisor()
        {
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
