// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // ProviderEscSchoolDistricts
    [Table("ProviderEscSchoolDistricts", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class ProviderEscSchoolDistrict: IEntity
    {
        // ProviderEscSchoolDistrict
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_ProviderEscSchoolDistricts", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"ProviderEscAssignmentId", Order = 2, TypeName = "int")]
        [Index(@"IX_ProviderEscSchoolDistricts_ProviderEscAssignmentId", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Provider esc assignment ID")]
        public int ProviderEscAssignmentId { get; set; } // ProviderEscAssignmentId

        [Column(@"SchoolDistrictId", Order = 3, TypeName = "int")]
        [Index(@"IX_ProviderEscSchoolDistricts_SchoolDistrictId", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "School district ID")]
        public int SchoolDistrictId { get; set; } // SchoolDistrictId

        // Foreign keys

        /// <summary>
        /// Parent ProviderEscAssignment pointed by [ProviderEscSchoolDistricts].([ProviderEscAssignmentId]) (FK_ProviderEscSchoolDistricts_ProviderEsc)
        /// </summary>
        [InverseProperty("ProviderEscSchoolDistricts")]
        [ForeignKey("ProviderEscAssignmentId")] public ProviderEscAssignment ProviderEscAssignment { get; set; } // FK_ProviderEscSchoolDistricts_ProviderEsc

        /// <summary>
        /// Parent SchoolDistrict pointed by [ProviderEscSchoolDistricts].([SchoolDistrictId]) (FK_ProviderEscSchoolDistricts_SchoolDistrict)
        /// </summary>
        [InverseProperty("ProviderEscSchoolDistricts")]
        [ForeignKey("SchoolDistrictId")] public SchoolDistrict SchoolDistrict { get; set; } // FK_ProviderEscSchoolDistricts_SchoolDistrict

        public ProviderEscSchoolDistrict()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
