// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // ProviderEmploymentTypes
    [Table("ProviderEmploymentTypes", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class ProviderEmploymentType: IEntity, IBasicNameEntity
    {
        // ProviderEmploymentType
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_ProviderEmploymentTypes", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"Name", Order = 2, TypeName = "varchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 20)

        // Reverse navigation

        /// <summary>
        /// Child Providers where [Providers].[ProviderEmploymentTypeId] point to this entity (FK_Providers_ProviderEmploymentTypes)
        /// </summary>
        public System.Collections.Generic.ICollection<Provider> Providers { get; set; } // Providers.FK_Providers_ProviderEmploymentTypes

        public ProviderEmploymentType()
        {
            Providers = new System.Collections.Generic.List<Provider>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
