// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // Providers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class ProviderConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Provider>
    {
        public ProviderConfiguration()
            : this("dbo")
        {
        }

        public ProviderConfiguration(string schema)
        {
            Property(x => x.OrpApprovalRequestDate).IsOptional();
            Property(x => x.OrpApprovalDate).IsOptional();
            Property(x => x.OrpDenialDate).IsOptional();
            Property(x => x.Npi).IsOptional().IsUnicode(false);
            Property(x => x.Phone).IsOptional().IsUnicode(false);
            Property(x => x.Notes).IsOptional().IsUnicode(false);
            Property(x => x.DocumentationDate).IsOptional();
            Property(x => x.ModifiedById).IsOptional();
            Property(x => x.DateCreated).IsOptional();
            Property(x => x.DateModified).IsOptional();
            Property(x => x.BlockedReason).IsOptional().IsUnicode(false);
            Property(x => x.DoNotBillReasonId).IsOptional();

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
