// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // ProviderStudents
    [Table("ProviderStudents", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class ProviderStudent: IEntity
    {
        // ProviderStudent
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_ProviderStudents", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"ProviderId", Order = 2, TypeName = "int")]
        [Index(@"IX_ProviderStudents_ProviderId", 1, IsUnique = false, IsClustered = false)]
        [Index(@"IX_ProviderStudents_StudentId_ProviderId", 2, IsUnique = false, IsClustered = false)]
        [Display(Name = "Provider ID")]
        public int ProviderId { get; set; } // ProviderId

        [Column(@"StudentId", Order = 3, TypeName = "int")]
        [Index(@"IX_ProviderStudents_StudentId_ProviderId", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Student ID")]
        public int StudentId { get; set; } // StudentId

        [Column(@"CreatedById", Order = 4, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"DateCreated", Order = 5, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [ProviderStudents].([CreatedById]) (FK_ProviderStudents_CreatedBy)
        /// </summary>
        [InverseProperty("ProviderStudents")]
        [ForeignKey("CreatedById")] public User User { get; set; } // FK_ProviderStudents_CreatedBy

        /// <summary>
        /// Parent Provider pointed by [ProviderStudents].([ProviderId]) (FK_ProviderStudents_Providers)
        /// </summary>
        [InverseProperty("ProviderStudents")]
        [ForeignKey("ProviderId")] public Provider Provider { get; set; } // FK_ProviderStudents_Providers

        /// <summary>
        /// Parent Student pointed by [ProviderStudents].([StudentId]) (FK_ProviderStudents_Students)
        /// </summary>
        [InverseProperty("ProviderStudents")]
        [ForeignKey("StudentId")] public Student Student { get; set; } // FK_ProviderStudents_Students

        public ProviderStudent()
        {
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
