// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // ReadMessages
    [Table("ReadMessages", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class ReadMessage: IEntity
    {
        // ReadMessage
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_ReadMessages", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"MessageId", Order = 2, TypeName = "int")]
        [Display(Name = "Message ID")]
        public int MessageId { get; set; } // MessageId

        [Column(@"ReadById", Order = 3, TypeName = "int")]
        [Display(Name = "Read by ID")]
        public int ReadById { get; set; } // ReadById

        [Column(@"DateRead", Order = 4, TypeName = "datetime")]
        [Display(Name = "Date read")]
        public System.DateTime DateRead { get; set; } // DateRead

        // Foreign keys

        /// <summary>
        /// Parent Message pointed by [ReadMessages].([MessageId]) (FK_ReadMessages_Message)
        /// </summary>
        [InverseProperty("ReadMessages")]
        [ForeignKey("MessageId")] public Message Message { get; set; } // FK_ReadMessages_Message

        /// <summary>
        /// Parent User pointed by [ReadMessages].([ReadById]) (FK_ReadMessages_ReadBy)
        /// </summary>
        [InverseProperty("ReadMessages")]
        [ForeignKey("ReadById")] public User User { get; set; } // FK_ReadMessages_ReadBy

        public ReadMessage()
        {
            DateRead = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
