// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // RosterValidationStudents
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class RosterValidationStudentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RosterValidationStudent>
    {
        public RosterValidationStudentConfiguration()
            : this("dbo")
        {
        }

        public RosterValidationStudentConfiguration(string schema)
        {
            Property(x => x.LastName).IsUnicode(false);
            Property(x => x.FirstName).IsUnicode(false);
            Property(x => x.IdentificationCode).IsOptional().IsUnicode(false);
            Property(x => x.ReferenceId).IsUnicode(false);
            Property(x => x.RejectReasonCode).IsOptional().IsUnicode(false);
            Property(x => x.FollowUpActionCode).IsOptional().IsUnicode(false);
            Property(x => x.Address).IsUnicode(false);
            Property(x => x.City).IsUnicode(false);
            Property(x => x.State).IsUnicode(false);
            Property(x => x.PostalCode).IsUnicode(false);
            Property(x => x.InsuredDateTimePeriod).IsUnicode(false);

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
