// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // ServiceOutcomes
    [Table("ServiceOutcomes", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class ServiceOutcome: IEntity
    {
        // ServiceOutcome
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_ServiceOutcomes", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"Notes", Order = 2, TypeName = "varchar")]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Notes")]
        public string Notes { get; set; } // Notes (length: 250)

        [Column(@"GoalId", Order = 3, TypeName = "int")]
        [Display(Name = "Goal ID")]
        public int GoalId { get; set; } // GoalId

        [Column(@"CreatedById", Order = 4, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int? CreatedById { get; set; } // CreatedById

        [Column(@"ModifiedById", Order = 5, TypeName = "int")]
        [Display(Name = "Modified by ID")]
        public int? ModifiedById { get; set; } // ModifiedById

        [Column(@"DateCreated", Order = 6, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        [Column(@"DateModified", Order = 7, TypeName = "datetime")]
        [Display(Name = "Date modified")]
        public System.DateTime? DateModified { get; set; } // DateModified

        [Column(@"Archived", Order = 8, TypeName = "bit")]
        [Display(Name = "Archived")]
        public bool Archived { get; set; } // Archived

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [ServiceOutcomes].([CreatedById]) (FK_ServiceOutcomes_CreatedBy)
        /// </summary>
        [InverseProperty("ServiceOutcomes_CreatedById")]
        [ForeignKey("CreatedById")] public User CreatedBy { get; set; } // FK_ServiceOutcomes_CreatedBy

        /// <summary>
        /// Parent Goal pointed by [ServiceOutcomes].([GoalId]) (FK_ServiceOutcomes_Goal)
        /// </summary>
        [InverseProperty("ServiceOutcomes")]
        [ForeignKey("GoalId")] public Goal Goal { get; set; } // FK_ServiceOutcomes_Goal

        /// <summary>
        /// Parent User pointed by [ServiceOutcomes].([ModifiedById]) (FK_ServiceOutcomes_ModifiedBy)
        /// </summary>
        [InverseProperty("ServiceOutcomes_ModifiedById")]
        [ForeignKey("ModifiedById")] public User ModifiedBy { get; set; } // FK_ServiceOutcomes_ModifiedBy

        public ServiceOutcome()
        {
            DateCreated = System.DateTime.UtcNow;
            Archived = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
