// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // ServiceUnitTimeSegments
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class ServiceUnitTimeSegmentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ServiceUnitTimeSegment>
    {
        public ServiceUnitTimeSegmentConfiguration()
            : this("dbo")
        {
        }

        public ServiceUnitTimeSegmentConfiguration(string schema)
        {
            Property(x => x.EndMinutes).IsOptional();
            Property(x => x.ServiceUnitRuleId).IsOptional();
            Property(x => x.CreatedById).IsOptional();
            Property(x => x.ModifiedById).IsOptional();
            Property(x => x.DateCreated).IsOptional();
            Property(x => x.DateModified).IsOptional();

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
