// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // StudentDistrictWithdrawals
    [Table("StudentDistrictWithdrawals", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class StudentDistrictWithdrawal: IEntity
    {
        // StudentDistrictWithdrawal
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_StudentDistrictWithdrawals", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"StudentId", Order = 2, TypeName = "int")]
        [Display(Name = "Student ID")]
        public int StudentId { get; set; } // StudentId

        [Column(@"DistrictId", Order = 3, TypeName = "int")]
        [Display(Name = "District ID")]
        public int DistrictId { get; set; } // DistrictId

        [Column(@"EnrollmentDate", Order = 4, TypeName = "datetime")]
        [Display(Name = "Enrollment date")]
        public System.DateTime? EnrollmentDate { get; set; } // EnrollmentDate

        [Column(@"WithdrawalDate", Order = 5, TypeName = "datetime")]
        [Display(Name = "Withdrawal date")]
        public System.DateTime? WithdrawalDate { get; set; } // WithdrawalDate

        [Column(@"Archived", Order = 6, TypeName = "bit")]
        [Display(Name = "Archived")]
        public bool Archived { get; set; } // Archived

        [Column(@"CreatedById", Order = 7, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"ModifiedById", Order = 8, TypeName = "int")]
        [Display(Name = "Modified by ID")]
        public int? ModifiedById { get; set; } // ModifiedById

        [Column(@"DateCreated", Order = 9, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        [Column(@"DateModified", Order = 10, TypeName = "datetime")]
        [Display(Name = "Date modified")]
        public System.DateTime? DateModified { get; set; } // DateModified

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [StudentDistrictWithdrawals].([CreatedById]) (FK_StudentDistrictWithdrawals_CreatedBy)
        /// </summary>
        [InverseProperty("StudentDistrictWithdrawals_CreatedById")]
        [ForeignKey("CreatedById")] public User CreatedBy { get; set; } // FK_StudentDistrictWithdrawals_CreatedBy

        /// <summary>
        /// Parent SchoolDistrict pointed by [StudentDistrictWithdrawals].([DistrictId]) (FK_StudentDistrictWithdrawals_SchoolDistrict)
        /// </summary>
        [InverseProperty("StudentDistrictWithdrawals")]
        [ForeignKey("DistrictId")] public SchoolDistrict SchoolDistrict { get; set; } // FK_StudentDistrictWithdrawals_SchoolDistrict

        /// <summary>
        /// Parent User pointed by [StudentDistrictWithdrawals].([ModifiedById]) (FK_StudentDistrictWithdrawals_ModifiedBy)
        /// </summary>
        [InverseProperty("StudentDistrictWithdrawals_ModifiedById")]
        [ForeignKey("ModifiedById")] public User ModifiedBy { get; set; } // FK_StudentDistrictWithdrawals_ModifiedBy

        /// <summary>
        /// Parent Student pointed by [StudentDistrictWithdrawals].([StudentId]) (FK_StudentDistrictWithdrawals_Student)
        /// </summary>
        [InverseProperty("StudentDistrictWithdrawals")]
        [ForeignKey("StudentId")] public Student Student { get; set; } // FK_StudentDistrictWithdrawals_Student

        public StudentDistrictWithdrawal()
        {
            Archived = false;
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
