// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // Students
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class StudentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Student>
    {
        public StudentConfiguration()
            : this("dbo")
        {
        }

        public StudentConfiguration(string schema)
        {
            Property(x => x.FirstName).IsUnicode(false);
            Property(x => x.MiddleName).IsOptional().IsUnicode(false);
            Property(x => x.LastName).IsUnicode(false);
            Property(x => x.StudentCode).IsOptional().IsUnicode(false);
            Property(x => x.MedicaidNo).IsOptional().IsUnicode(false);
            Property(x => x.Grade).IsUnicode(false);
            Property(x => x.Notes).IsOptional().IsUnicode(false);
            Property(x => x.AddressId).IsOptional();
            Property(x => x.DistrictId).IsOptional();
            Property(x => x.EnrollmentDate).IsOptional();
            Property(x => x.EscId).IsOptional();
            Property(x => x.ModifiedById).IsOptional();
            Property(x => x.DateCreated).IsOptional();
            Property(x => x.DateModified).IsOptional();

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
