// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // StudentParentalConsentTypes
    [Table("StudentParentalConsentTypes", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class StudentParentalConsentType: IEntity, IBasicNameEntity
    {
        // StudentParentalConsentType
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_StudentParentalConsentTypes", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"Name", Order = 2, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child StudentParentalConsents where [StudentParentalConsents].[ParentalConsentTypeId] point to this entity (FK_StudentParentalConsents_StudentParentalConsentType)
        /// </summary>
        public System.Collections.Generic.ICollection<StudentParentalConsent> StudentParentalConsents { get; set; } // StudentParentalConsents.FK_StudentParentalConsents_StudentParentalConsentType

        public StudentParentalConsentType()
        {
            StudentParentalConsents = new System.Collections.Generic.List<StudentParentalConsent>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
