// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // StudentDisabilityCodes
    [Table("StudentDisabilityCodes", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class StudentDisabilityCode: IEntity
    {
        // StudentDisabilityCode
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_StudentDisabilityCodes", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"StudentId", Order = 2, TypeName = "int")]
        [Display(Name = "Student ID")]
        public int StudentId { get; set; } // StudentId

        [Column(@"DisabilityCodeId", Order = 3, TypeName = "int")]
        [Display(Name = "Disability code ID")]
        public int DisabilityCodeId { get; set; } // DisabilityCodeId

        [Column(@"Archived", Order = 4, TypeName = "bit")]
        [Display(Name = "Archived")]
        public bool Archived { get; set; } // Archived

        [Column(@"CreatedById", Order = 5, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"ModifiedById", Order = 6, TypeName = "int")]
        [Display(Name = "Modified by ID")]
        public int? ModifiedById { get; set; } // ModifiedById

        [Column(@"DateCreated", Order = 7, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        [Column(@"DateModified", Order = 8, TypeName = "datetime")]
        [Display(Name = "Date modified")]
        public System.DateTime? DateModified { get; set; } // DateModified

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [StudentDisabilityCodes].([CreatedById]) (FK_StudentDisabilityCodes_CreatedBy)
        /// </summary>
        [InverseProperty("StudentDisabilityCodes_CreatedById")]
        [ForeignKey("CreatedById")] public User CreatedBy { get; set; } // FK_StudentDisabilityCodes_CreatedBy

        /// <summary>
        /// Parent DisabilityCode pointed by [StudentDisabilityCodes].([DisabilityCodeId]) (FK_StudentDisabilityCodes_DisabilityCodes)
        /// </summary>
        [InverseProperty("StudentDisabilityCodes")]
        [ForeignKey("DisabilityCodeId")] public DisabilityCode DisabilityCode { get; set; } // FK_StudentDisabilityCodes_DisabilityCodes

        /// <summary>
        /// Parent User pointed by [StudentDisabilityCodes].([ModifiedById]) (FK_StudentDisabilityCodes_ModifiedBy)
        /// </summary>
        [InverseProperty("StudentDisabilityCodes_ModifiedById")]
        [ForeignKey("ModifiedById")] public User ModifiedBy { get; set; } // FK_StudentDisabilityCodes_ModifiedBy

        /// <summary>
        /// Parent Student pointed by [StudentDisabilityCodes].([StudentId]) (FK_StudentDisabilityCodes_Student)
        /// </summary>
        [InverseProperty("StudentDisabilityCodes")]
        [ForeignKey("StudentId")] public Student Student { get; set; } // FK_StudentDisabilityCodes_Student

        public StudentDisabilityCode()
        {
            Archived = false;
            CreatedById = 1;
            DateCreated = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
