// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // SupervisorProviderStudentReferalSignOffs
    [Table("SupervisorProviderStudentReferalSignOffs", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class SupervisorProviderStudentReferalSignOff: IEntity
    {
        // SupervisorProviderStudentReferalSignOff

        ///<summary>
        /// Module
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_SupervisorProviderStudentReferalSignOff", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"SupervisorId", Order = 2, TypeName = "int")]
        [Display(Name = "Supervisor ID")]
        public int SupervisorId { get; set; } // SupervisorId

        [Column(@"StudentId", Order = 3, TypeName = "int")]
        [Index(@"IX_SupervisorProviderStudentReferalSignOffs_1", 1, IsUnique = false, IsClustered = false)]
        [Index(@"IX_SupervisorProviderStudentReferalSignOffs_StudentId_ServiceCodeId", 1, IsUnique = false, IsClustered = false)]
        [Index(@"IX_SupervisorProviderStudentReferalSignOffs_2", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Student ID")]
        public int StudentId { get; set; } // StudentId

        [Column(@"SignOffText", Order = 4, TypeName = "varchar")]
        [MaxLength(1000)]
        [StringLength(1000)]
        [Display(Name = "Sign off text")]
        public string SignOffText { get; set; } // SignOffText (length: 1000)

        [Column(@"SignOffDate", Order = 5, TypeName = "datetime")]
        [Index(@"IX_SupervisorProviderStudentReferalSignOffs_1", 2, IsUnique = false, IsClustered = false)]
        [Display(Name = "Sign off date")]
        public System.DateTime? SignOffDate { get; set; } // SignOffDate

        [Column(@"SignedOffById", Order = 6, TypeName = "int")]
        [Display(Name = "Signed off by ID")]
        public int? SignedOffById { get; set; } // SignedOffById

        [Column(@"ServiceCodeId", Order = 7, TypeName = "int")]
        [Index(@"IX_SupervisorProviderStudentReferalSignOffs_StudentId_ServiceCodeId", 2, IsUnique = false, IsClustered = false)]
        [Display(Name = "Service code ID")]
        public int? ServiceCodeId { get; set; } // ServiceCodeId

        [Column(@"EffectiveDateFrom", Order = 8, TypeName = "datetime")]
        [Display(Name = "Effective date from")]
        public System.DateTime? EffectiveDateFrom { get; set; } // EffectiveDateFrom

        [Column(@"EffectiveDateTo", Order = 9, TypeName = "datetime")]
        [Display(Name = "Effective date to")]
        public System.DateTime? EffectiveDateTo { get; set; } // EffectiveDateTo

        [Column(@"CreatedById", Order = 10, TypeName = "int")]
        [Display(Name = "Created by ID")]
        public int CreatedById { get; set; } // CreatedById

        [Column(@"ModifiedById", Order = 11, TypeName = "int")]
        [Display(Name = "Modified by ID")]
        public int? ModifiedById { get; set; } // ModifiedById

        [Column(@"DateCreated", Order = 12, TypeName = "datetime")]
        [Display(Name = "Date created")]
        public System.DateTime? DateCreated { get; set; } // DateCreated

        [Column(@"DateModified", Order = 13, TypeName = "datetime")]
        [Display(Name = "Date modified")]
        public System.DateTime? DateModified { get; set; } // DateModified

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [SupervisorProviderStudentReferalSignOffs].([CreatedById]) (FK_SupervisorProviderStudentReferalSignOff_CreatedBy)
        /// </summary>
        [InverseProperty("SupervisorProviderStudentReferalSignOffs_CreatedById")]
        [ForeignKey("CreatedById")] public User CreatedBy { get; set; } // FK_SupervisorProviderStudentReferalSignOff_CreatedBy

        /// <summary>
        /// Parent User pointed by [SupervisorProviderStudentReferalSignOffs].([ModifiedById]) (FK_SupervisorProviderStudentReferalSignOff_ModifiedBy)
        /// </summary>
        [InverseProperty("SupervisorProviderStudentReferalSignOffs_ModifiedById")]
        [ForeignKey("ModifiedById")] public User ModifiedBy { get; set; } // FK_SupervisorProviderStudentReferalSignOff_ModifiedBy

        /// <summary>
        /// Parent ServiceCode pointed by [SupervisorProviderStudentReferalSignOffs].([ServiceCodeId]) (FK_SupervisorProviderStudentReferalSignOff_ServiceCode)
        /// </summary>
        [InverseProperty("SupervisorProviderStudentReferalSignOffs")]
        [ForeignKey("ServiceCodeId")] public ServiceCode ServiceCode { get; set; } // FK_SupervisorProviderStudentReferalSignOff_ServiceCode

        /// <summary>
        /// Parent User pointed by [SupervisorProviderStudentReferalSignOffs].([SignedOffById]) (FK_SupervisorProviderStudentReferalSignOff_SignedOffBy)
        /// </summary>
        [InverseProperty("SupervisorProviderStudentReferalSignOffs_SignedOffById")]
        [ForeignKey("SignedOffById")] public User SignedOffBy { get; set; } // FK_SupervisorProviderStudentReferalSignOff_SignedOffBy

        /// <summary>
        /// Parent Student pointed by [SupervisorProviderStudentReferalSignOffs].([StudentId]) (FK_SupervisorProviderStudentReferalSignOff_Student)
        /// </summary>
        [InverseProperty("SupervisorProviderStudentReferalSignOffs")]
        [ForeignKey("StudentId")] public Student Student { get; set; } // FK_SupervisorProviderStudentReferalSignOff_Student

        /// <summary>
        /// Parent Provider pointed by [SupervisorProviderStudentReferalSignOffs].([SupervisorId]) (FK_SupervisorProviderStudentReferalSignOff_Supervisor)
        /// </summary>
        [InverseProperty("SupervisorProviderStudentReferalSignOffs")]
        [ForeignKey("SupervisorId")] public Provider Supervisor { get; set; } // FK_SupervisorProviderStudentReferalSignOff_Supervisor

        public SupervisorProviderStudentReferalSignOff()
        {
            DateCreated = System.DateTime.UtcNow;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
