// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // UnmatchedClaimDistricts
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class UnmatchedClaimDistrictConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UnmatchedClaimDistrict>
    {
        public UnmatchedClaimDistrictConfiguration()
            : this("dbo")
        {
        }

        public UnmatchedClaimDistrictConfiguration(string schema)
        {
            Property(x => x.IdentificationCode).IsUnicode(false);
            Property(x => x.DistrictOrganizationName).IsUnicode(false);
            Property(x => x.Address).IsUnicode(false);
            Property(x => x.City).IsUnicode(false);
            Property(x => x.State).IsUnicode(false);
            Property(x => x.PostalCode).IsUnicode(false);
            Property(x => x.EmployerId).IsUnicode(false);

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
