// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // UserTypes
    [Table("UserTypes", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class UserType: IEntity, IBasicNameEntity
    {
        // UserType
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_UserTypes", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"Name", Order = 2, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child ClaimTypes (Many-to-Many) mapped by table [UserTypesClaimTypes]
        /// </summary>
        public System.Collections.Generic.ICollection<ClaimType> ClaimTypes { get; set; } // Many to many mapping
        /// <summary>
        /// Child UserRoles where [UserRoles].[UserTypeId] point to this entity (FK_UserRoles_UserType)
        /// </summary>
        public System.Collections.Generic.ICollection<UserRole> UserRoles { get; set; } // UserRoles.FK_UserRoles_UserType

        public UserType()
        {
            UserRoles = new System.Collections.Generic.List<UserRole>();
            ClaimTypes = new System.Collections.Generic.List<ClaimType>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
