// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // Vouchers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class VoucherConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Voucher>
    {
        public VoucherConfiguration()
            : this("dbo")
        {
        }

        public VoucherConfiguration(string schema)
        {
            Property(x => x.VoucherAmount).IsUnicode(false);
            Property(x => x.PaidAmount).IsUnicode(false);
            Property(x => x.ServiceCode).IsOptional().IsUnicode(false);
            Property(x => x.SchoolDistrictId).IsOptional();
            Property(x => x.UnmatchedClaimDistrictId).IsOptional();
            Property(x => x.SchoolYear).IsUnicode(false);

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
