// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    using TrackerEnabledDbContext;

    // VoucherTypes
    [Table("VoucherTypes", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.0.0")]
    public partial class VoucherType: IEntity, IBasicNameEntity
    {
        // VoucherType
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_VoucherTypes", 1, IsUnique = true, IsClustered = true)]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"Name", Order = 2, TypeName = "varchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 100)

        [Column(@"Sort", Order = 3, TypeName = "int")]
        [Display(Name = "Sort")]
        public int? Sort { get; set; } // Sort

        [Column(@"Editable", Order = 4, TypeName = "bit")]
        [Display(Name = "Editable")]
        public bool Editable { get; set; } // Editable

        // Reverse navigation

        /// <summary>
        /// Child Vouchers where [Vouchers].[VoucherTypeId] point to this entity (FK_Vouchers_VoucherTypes)
        /// </summary>
        public System.Collections.Generic.ICollection<Voucher> Vouchers { get; set; } // Vouchers.FK_Vouchers_VoucherTypes

        public VoucherType()
        {
            Sort = 2;
            Editable = true;
            Vouchers = new System.Collections.Generic.List<Voucher>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
